// EDIT TEXTS: update static multilingual copy here. Keep keys aligned with data-i18n attributes in index.html.
const translations = {
  en: {
    skip: "Skip to content",
    "nav.villa": "The Villa",
    "nav.story": "Story",
    "nav.views": "Views",
    "nav.location": "Location",
    "nav.book": "Book",
    "hero.eyebrow": "Raito, the Amalfi Coast's best-kept secret",
    "hero.title": "Villa San Vito",
    "hero.subtitle": "A private sea-view villa above Vietri sul Mare, where the Amalfi Coast feels slower, quieter and more intimate.",
    "buttons.discover": "Discover the villa",
    "buttons.platforms": "See booking platforms",
    "buttons.airbnb": "Open Airbnb listing",
    "buttons.booking": "Open Booking listing",
    "buttons.vrbo": "Open Vrbo listing",
    "trust.platforms": "Reservations through trusted platforms",
    "trust.private": "Private villa, not a hotel",
    "trust.sea": "Sea views over the Gulf of Salerno",
    "facts.terraceLabel": "Terrace",
    "facts.terrace": "Open-air mornings",
    "facts.gulfLabel": "Gulf",
    "facts.gulf": "Sea-facing light",
    "facts.gardenLabel": "Garden",
    "facts.garden": "Lemon tree and shade",
    "facts.raitoLabel": "Raito",
    "facts.raito": "A quiet village base",
    "facts.homeLabel": "Home",
    "facts.home": "Private and lived-in",
    "facts.tableLabel": "Table",
    "facts.table": "Meals without hurry",
    "facts.parkingLabel": "Parking",
    "facts.parking": "Inside the property",
    "earlyPhotos.terrace": "The terrace, the Gulf and the first slow morning",
    "earlyPhotos.detail": "Small details, quiet light",
    "earlyPhotos.sign": "A private entrance in Raito",
    "story.kicker": "The perfect corner to enjoy the Amalfi Coast",
    "story.title": "Some trips fill the camera roll.\nAnd some experiences slow time down and remind us what life is about",
    "story.p1": "In Raito, the rush stays on the cliffs. Everything here invites serenity and pleasure.",
    "story.p2": "The Amalfi Coast is not only visited: it is felt.",
    "story.p3": "Villa San Vito is the ideal refuge for discovering southern Italy at another rhythm. A corner of pure beauty, where the day is measured in the breath of terrace breeze, the time it takes coffee to cool, and the hours the afternoon takes before handing itself to night and stars.",
    "story.p4": "Just within reach of Amalfi, Positano and Ravello, the villa brings together nature, privacy and hand-painted views. Three levels designed for sharing, resting and disconnecting: generous interiors, private gardens, unforgettable terraces and nights when the sea seems to blend with the silence.",
    "story.p5": "Here, breakfasts last for hours. Conversations stretch beneath the stars. And every corner invites you to stay one more day.",
    "story.p6": "Ideal for families, groups of friends or travelers looking for more than accommodation: a way to live Italy from within.",
    "story.signature": "Villa San Vito. Your home on the Amalfi Coast.",
    "history.kicker": "Raito, sunlit memory",
    "history.title": "A village suspended between mountain, sea and time",
    "history.caption": "Raito and Vietri in an 1819 painting by Josef Rabel.",
    "history.p1": "The name Raito carries an old suggestion of sunlight. Set above Vietri sul Mare, the village opens toward the Gulf of Salerno and sits between rock, lemon trees and the quiet blue of the coast.",
    "history.p2": "Villa San Vito belongs to that landscape. An old nineteenth-century home, it preserves the atmosphere of local architecture: stone, terraces, shade, sea air and rooms made to stay cool through long Mediterranean days.",
    "history.p3": "Its story is not separate from the place around it. To arrive here is to step into Raito's slower rhythm, where the coast is seen from above and the evening light turns the villa into a small balcony over the Gulf.",
    "slow.kicker": "Mediterranean stillness",
    "slow.title": "A slower rhythm above the Gulf of Salerno",
    "slow.copy": "Villa San Vito has nothing in common with the polished routine of large hotels. Its spirit belongs to calm and the senses, to the pace of the body and the heart.",
    "seo.kicker": "A private stay on the Amalfi Coast",
    "seo.title": "Villa San Vito is not a hotel or a resort. It is an Italian coastal experience.",
    "seo.copy": "For travelers wondering where to stay on the Amalfi Coast and comparing hotels, boutique stays, resorts or vacation rentals, Villa San Vito offers a different answer: the privacy of a private villa, generous indoor and outdoor spaces, and sea views over the Gulf of Salerno. It is not all-inclusive and it is not a hotel; it is a more personal Mediterranean stay for those who prefer space, silence and a real connection with the coast.",
    "compare.kicker": "The Villa San Vito experience",
    "compare.title": "A slower way to belong to the coast",
    "compare.card1.title": "Morning on the terrace",
    "compare.card1.copy": "Coffee, sea air and the Gulf slowly brightening below Raito.",
    "compare.card2.title": "Shade in the garden",
    "compare.card2.copy": "A lemon tree, quiet corners and enough room for everyone to disappear for a while.",
    "compare.card3.title": "Lunch without a clock",
    "compare.card3.copy": "The kitchen, the table and the terrace make simple meals feel like part of the landscape.",
    "compare.card4.title": "Evenings above the lights",
    "compare.card4.copy": "Return from the coast to a calmer village and watch the Gulf become night.",
    "compare.card5.title": "A home base with soul",
    "compare.card5.copy": "Private, personal and rooted in the architecture and pace of southern Italy.",
    "audience.kicker": "For couples, families and slow-travel lovers",
    "audience.title": "A coastal villa for a different kind of trip",
    "audience.copy": "Villa San Vito is perfect for couples looking for a romantic escape, friends planning a slower coastal stay, and families or small groups who want a homelike experience. Here, you can live a little more like an Italian: slowly, quietly, looking at the sea through lemon trees, with good food, open air and an unforgettable glass of wine.",
    "villa.kicker": "The villa",
    "villa.title": "A house to inhabit slowly",
    "villa.copy": "The villa is arranged for the rituals that matter on the coast: waking with the light, gathering around the table, resting in the cool interiors and returning outside whenever the sea asks for attention.",
    "villa.caption": "Garden shade, terraces and quiet outdoor living.",
    "villa.moment1.label": "Outside",
    "villa.moment1.title": "Terraces, garden and Gulf views",
    "villa.moment1.copy": "The outdoor spaces carry the spirit of the house: open air, lemon leaves, long conversations and the sea always nearby.",
    "villa.moment2.label": "Inside",
    "villa.moment2.title": "Cool rooms for resting between excursions",
    "villa.moment2.copy": "Interiors are shown lightly here, just enough to understand the comfort of the property without turning the site into a room catalogue.",
    "villa.moment3.label": "Together",
    "villa.moment3.title": "A table, a kitchen and time to share",
    "villa.moment3.copy": "Villa San Vito works best when days are allowed to stretch: breakfast outside, lunch after the market, wine as the coast grows quiet.",
    "villa.practical": "Practical layout, capacity and amenity details are available on Airbnb, Booking and Vrbo, where reservations are completed.",
    "gallery.kicker": "Views, textures and quiet corners",
    "gallery.title": "A few images to set the mood",
    "gallery.note": "A small editorial selection: terrace, garden, table, tiles and details. Interiors appear only as orientation, not as a catalogue.",
    "gallery.item1": "Garden terrace",
    "gallery.item2": "Terrace over the Gulf",
    "gallery.item3": "Table set for slow meals",
    "gallery.item4": "Kitchen tilework",
    "gallery.item5": "Lemon tree above the Gulf",
    "gallery.item6": "Blue arch and stair light",
    "location.kicker": "Location",
    "location.title": "Raito, above Vietri sul Mare",
    "location.copy": "Raito is a quiet village above Vietri sul Mare, known for its views, calm atmosphere and proximity to Salerno. From here, guests can explore the Amalfi Coast while returning to a private and peaceful home base at the end of the day.",
    "location.note": "The website shows the general area. Exact address details can be managed through the booking platform.",
    "nearby.kicker": "Explore the coast",
    "nearby.title": "The perfect base for exploring the best of the Amalfi Coast",
    "nearby.intro": "From Villa San Vito, you can spend the day discovering some of the most beautiful places in the area.",
    "nearby.vietri": "A nearby coastal town known for ceramics, sea views and relaxed local character.",
    "nearby.salerno": "A practical gateway for transport, dining and waterfront walks near the Amalfi Coast.",
    "nearby.amalfi": "A classic Amalfi Coast stop and a beautiful day trip from the villa.",
    "nearby.ravello": "A refined hill town loved for gardens, views and cultural heritage.",
    "nearby.positano": "A famous vertical seaside village reachable as part of a coastal itinerary.",
    "nearby.pompeii": "An essential archaeological site for travelers interested in Roman history.",
    "nearby.paestum": "A rewarding day trip for Greek temples, archaeology and open landscapes.",
    "booking.kicker": "Reservations",
    "booking.title": "When you are ready, choose your platform",
    "booking.copy": "This website is a calm introduction to the villa. Availability, payments, policies and reservations are handled externally by Airbnb, Booking and Vrbo.",
    "booking.airbnb.copy": "See the listing, guest notes and reservation details.",
    "booking.booking.copy": "Check availability, policies and traveler information.",
    "booking.vrbo.copy": "View the Vrbo page and reservation details.",
    "booking.disclaimer": "This website is an informational showcase for Villa San Vito. Direct bookings are not processed here.",
    "reviews.kicker": "Verified reviews",
    "reviews.title": "What stays with guests",
    "reviews.label": "Guest note",
    "reviews.airbnb": "Verified on Airbnb",
    "reviews.count": "14 verified reviews",
    "reviews.highlights": "The recurring memory is simple: the view, the outdoor space, the calm location and the ease of returning to a real house after the coast.",
    "reviews.placeholder": "This is a very good place. Spectacular view from a huge backyard. The accommodation was in good condition. Highly recommended. The parking is a little narrow, but we were properly informed about that, so there were no surprises.",
    "reviews.link": "Read reviews on Airbnb",
    "reviews.note": "Full review history and platform details are available on the reservation listings.",
    "faq.kicker": "Before you book",
    "faq.title": "Frequently asked questions",
    "faq.1.q": "Can I reserve directly on this website?",
    "faq.1.a": "No. This website is only an editorial showcase for Villa San Vito. Reservations are completed through Airbnb, Booking or Vrbo.",
    "faq.2.q": "What kind of stay is Villa San Vito?",
    "faq.2.a": "It is a private villa in Raito for travelers who prefer terraces, garden shade, sea views and a slower local atmosphere.",
    "faq.3.q": "Where is the villa located?",
    "faq.3.a": "Villa San Vito is in Raito, above Vietri sul Mare, with views toward the Gulf of Salerno and access to the Amalfi Coast from a quieter village base.",
    "faq.4.q": "Where can I find practical details?",
    "faq.4.a": "Capacity, amenities, policies, availability and confirmed reservation details are kept on the external platform listings.",
    "footer.reservations": "Reservations are managed exclusively through Airbnb, Booking and Vrbo."
  },
  es: {
    skip: "Saltar al contenido",
    "nav.villa": "La Villa",
    "nav.story": "Historia",
    "nav.views": "Vistas",
    "nav.location": "Ubicación",
    "nav.book": "Reservar",
    "hero.eyebrow": "Raito, el secreto mejor guardado de la Costa Amalfitana",
    "hero.title": "Villa San Vito",
    "hero.subtitle": "Una villa privada con vista al mar sobre Vietri sul Mare, donde la Costa Amalfitana se siente más lenta, tranquila e íntima.",
    "buttons.discover": "Descubrir la villa",
    "buttons.platforms": "Ver plataformas de reserva",
    "buttons.airbnb": "Abrir anuncio en Airbnb",
    "buttons.booking": "Abrir anuncio en Booking",
    "buttons.vrbo": "Abrir anuncio en Vrbo",
    "trust.platforms": "Reservas a través de plataformas confiables",
    "trust.private": "Villa privada, no hotel",
    "trust.sea": "Vistas al Golfo de Salerno",
    "facts.terraceLabel": "Terraza",
    "facts.terrace": "Mañanas al aire libre",
    "facts.gulfLabel": "Golfo",
    "facts.gulf": "Luz mirando al mar",
    "facts.gardenLabel": "Jardín",
    "facts.garden": "Limonero y sombra",
    "facts.raitoLabel": "Raito",
    "facts.raito": "Base de pueblo tranquilo",
    "facts.homeLabel": "Casa",
    "facts.home": "Privada y vivida",
    "facts.tableLabel": "Mesa",
    "facts.table": "Comidas sin apuro",
    "facts.parkingLabel": "Parking",
    "facts.parking": "Dentro de la propiedad",
    "earlyPhotos.terrace": "La terraza, el Golfo y la primera mañana sin apuro",
    "earlyPhotos.detail": "Pequeños detalles, luz tranquila",
    "earlyPhotos.sign": "Una entrada privada en Raito",
    "story.kicker": "El rincón perfecto para disfrutar la Costa Amalfitana",
    "story.title": "Hay viajes que llenan la cámara de fotos.\nY experiencias que detienen el tiempo y nos recuerdan de qué se trata la vida",
    "story.p1": "En Raito, la prisa se queda en los acantilados. Todo, allí, invita a la serenidad y al placer.",
    "story.p2": "La Costa Amalfitana no se visita: se siente.",
    "story.p3": "Villa San Vito es el refugio ideal para descubrir el sur de Italia a otro ritmo. Un rincón de pura belleza, donde el día se mide en el suspiro de la brisa de la terraza, el tiempo que demora el café en enfriarse y las horas que se toma la tarde hasta entregar la noche y sus estrellas.",
    "story.p4": "A pocos minutos de Amalfi, Positano y Ravello, la villa combina naturaleza, privacidad y vistas que parecen pintadas a mano. Tres niveles diseñados para compartir, descansar y desconectarse: interiores amplios, jardines privados, terrazas inolvidables y noches en las que el mar parece mezclarse con el silencio.",
    "story.p5": "Acá los desayunos duran horas. Las charlas se alargan bajo las estrellas. Y cada rincón invita a quedarse un día más.",
    "story.p6": "Ideal para familias, grupos de amigos o viajeros que buscan algo más que hospedarse: vivir Italia desde adentro.",
    "story.signature": "Villa San Vito. Tu casa en la Costa Amalfitana.",
    "history.kicker": "Raito, memoria bañada por el sol",
    "history.title": "Un pueblo suspendido entre montaña, mar y tiempo",
    "history.caption": "Raito y Vietri en una pintura de 1819 de Josef Rabel.",
    "history.p1": "El nombre Raito conserva una antigua idea de luz. Situado sobre Vietri sul Mare, el pueblo se abre al Golfo de Salerno y descansa entre la roca, los limoneros y el azul tranquilo de la costa.",
    "history.p2": "Villa San Vito pertenece a ese paisaje. Antigua casa del siglo XIX, conserva la atmósfera de la arquitectura local: piedra, terrazas, sombra, aire de mar y ambientes pensados para mantenerse frescos durante los largos días mediterráneos.",
    "history.p3": "Su historia no está separada del lugar que la rodea. Llegar aquí es entrar en el ritmo más lento de Raito, donde la costa se mira desde lo alto y la luz de la tarde convierte la villa en un pequeño balcón sobre el Golfo.",
    "slow.kicker": "Quietud mediterránea",
    "slow.title": "Un ritmo más lento sobre el Golfo de Salerno",
    "slow.copy": "Villa San Vito no tiene nada en común con la rutina pulida de los grandes hoteles. Su propuesta tiene que ver con la calma y los sentidos. Con los tiempos del cuerpo y el corazón.",
    "seo.kicker": "Una estadía privada en la Costa Amalfitana",
    "seo.title": "Villa San Vito no es un hotel, ni un resort. Es una experiencia italiana.",
    "seo.copy": "Para viajeros que están decidiendo dónde alojarse en la Costa Amalfitana y comparan hoteles, alojamientos boutique, resorts o alquileres vacacionales, Villa San Vito ofrece otra respuesta: la privacidad de una villa, espacios interiores y exteriores amplios, y vistas al Golfo de Salerno. No es todo incluido y no es un hotel; es una estadía mediterránea más personal para quienes prefieren espacio, silencio y una conexión real con la costa.",
    "compare.kicker": "Experiencia San Vito",
    "compare.title": "Una forma más lenta de pertenecer a la costa",
    "compare.card1.title": "Mañana en la terraza",
    "compare.card1.copy": "Café, aire de mar y el Golfo iluminándose despacio debajo de Raito.",
    "compare.card2.title": "Sombra en el jardín",
    "compare.card2.copy": "Un limonero, rincones tranquilos y espacio para que cada uno desaparezca un rato.",
    "compare.card3.title": "Almuerzo sin reloj",
    "compare.card3.copy": "La cocina, la mesa y la terraza hacen que una comida simple se sienta parte del paisaje.",
    "compare.card4.title": "Atardeceres sobre las luces",
    "compare.card4.copy": "Volver desde la costa a un pueblo más calmo y mirar cómo el Golfo se vuelve noche.",
    "compare.card5.title": "Una base con alma",
    "compare.card5.copy": "Privada, personal y arraigada en la arquitectura y el ritmo del sur de Italia.",
    "audience.kicker": "Para parejas, familias y amantes del slow travel",
    "audience.title": "Una villa costera para un viaje diferente",
    "audience.copy": "Villa San Vito es perfecta para parejas que buscan una escapada romántica, amigos que quieren una estadía más lenta junto a la costa, y familias o grupos pequeños que prefieren una experiencia hogareña. Aquí puedes vivir como un italiano más: despacio, tranquilo, mirando el mar entre limoneros, con buena comida, aire libre y una inolvidable copa de vino.",
    "villa.kicker": "La villa",
    "villa.title": "Una casa para habitar despacio",
    "villa.copy": "La villa está pensada para los rituales que importan en la costa: despertar con la luz, reunirse alrededor de la mesa, descansar en interiores frescos y volver afuera cada vez que el mar pide atención.",
    "villa.caption": "Sombra de jardín, terrazas y vida tranquila al aire libre.",
    "villa.moment1.label": "Afuera",
    "villa.moment1.title": "Terrazas, jardín y vistas al Golfo",
    "villa.moment1.copy": "Los espacios exteriores llevan el espíritu de la casa: aire libre, hojas de limonero, conversaciones largas y el mar siempre cerca.",
    "villa.moment2.label": "Adentro",
    "villa.moment2.title": "Ambientes frescos para descansar entre paseos",
    "villa.moment2.copy": "Los interiores aparecen de forma sutil, solo lo suficiente para entender la comodidad de la propiedad sin convertir el sitio en un catálogo de habitaciones.",
    "villa.moment3.label": "Juntos",
    "villa.moment3.title": "Una mesa, una cocina y tiempo para compartir",
    "villa.moment3.copy": "Villa San Vito funciona mejor cuando los días se estiran: desayuno afuera, almuerzo después del mercado, vino cuando la costa se queda en silencio.",
    "villa.practical": "Los detalles prácticos de distribución, capacidad y servicios están disponibles en Airbnb, Booking y Vrbo, donde se completan las reservas.",
    "gallery.kicker": "Vistas, texturas y rincones tranquilos",
    "gallery.title": "Unas pocas imágenes para entrar en clima",
    "gallery.note": "Una selección editorial pequeña: terraza, jardín, mesa, azulejos y detalles. Los interiores aparecen solo como orientación, no como catálogo.",
    "gallery.item1": "Terraza del jardín",
    "gallery.item2": "Terraza sobre el Golfo",
    "gallery.item3": "Mesa para comidas sin prisa",
    "gallery.item4": "Azulejos de la cocina",
    "gallery.item5": "Limonero sobre el Golfo",
    "gallery.item6": "Arco azul y luz de escalera",
    "location.kicker": "Ubicación",
    "location.title": "Raito, sobre Vietri sul Mare",
    "location.copy": "Raito es un pueblo tranquilo sobre Vietri sul Mare, conocido por sus vistas, su calma y su cercanía a Salerno. Desde aquí, los huéspedes pueden explorar la Costa Amalfitana y volver al final del día a una base privada y serena.",
    "location.note": "El sitio muestra la zona general. Los detalles exactos de dirección pueden gestionarse desde la plataforma de reserva.",
    "nearby.kicker": "Explorar la costa",
    "nearby.title": "La base perfecta para recorrer lo mejor de la Costa Amalfitana",
    "nearby.intro": "Desde Villa San Vito, puedes visitar en el día los lugares más bellos de la zona.",
    "nearby.vietri": "Un pueblo costero cercano, reconocido por sus cerámicas, vistas al mar y carácter local.",
    "nearby.salerno": "Una base práctica para transporte, gastronomía y paseos junto al mar cerca de la Costa Amalfitana.",
    "nearby.amalfi": "Una parada clásica de la Costa Amalfitana y una hermosa excursión desde la villa.",
    "nearby.ravello": "Un pueblo de altura refinado, famoso por jardines, vistas y patrimonio cultural.",
    "nearby.positano": "Un célebre pueblo vertical junto al mar, alcanzable dentro de un itinerario costero.",
    "nearby.pompeii": "Un sitio arqueológico esencial para viajeros interesados en la historia romana.",
    "nearby.paestum": "Una excursión valiosa para ver templos griegos, arqueología y paisajes abiertos.",
    "booking.kicker": "Reservas",
    "booking.title": "Cuando estés listo, elige tu plataforma",
    "booking.copy": "Este sitio es una introducción tranquila a la villa. La disponibilidad, los pagos, las políticas y las reservas se gestionan externamente en Airbnb, Booking y Vrbo.",
    "booking.airbnb.copy": "Ver el anuncio, notas de huéspedes y detalles de reserva.",
    "booking.booking.copy": "Consultar disponibilidad, políticas e información para viajeros.",
    "booking.vrbo.copy": "Ver la página de Vrbo y los detalles de reserva.",
    "booking.disclaimer": "Este sitio web es una vidriera informativa de Villa San Vito. Aquí no se procesan reservas directas.",
    "reviews.kicker": "Reseñas verificadas",
    "reviews.title": "Lo que queda en quienes se alojan",
    "reviews.label": "Nota de huéspedes",
    "reviews.airbnb": "Verificado en Airbnb",
    "reviews.count": "14 reseñas verificadas",
    "reviews.highlights": "El recuerdo que se repite es simple: la vista, el espacio exterior, la ubicación tranquila y la facilidad de volver a una casa real después de recorrer la costa.",
    "reviews.placeholder": "Este es un muy buen lugar. Vista espectacular desde un patio trasero enorme. El alojamiento estaba en buenas condiciones. Muy recomendable. El estacionamiento es un poco estrecho, pero nos avisaron bien de eso. Así que no hubo sorpresas.",
    "reviews.link": "Ver reseñas en Airbnb",
    "reviews.note": "El historial completo de reseñas y los detalles de cada plataforma están disponibles en los anuncios de reserva.",
    "faq.kicker": "Antes de reservar",
    "faq.title": "Preguntas frecuentes",
    "faq.1.q": "¿Puedo reservar directamente en este sitio?",
    "faq.1.a": "No. Este sitio es solo una presentación editorial de Villa San Vito. Las reservas se completan a través de Airbnb, Booking o Vrbo.",
    "faq.2.q": "¿Qué tipo de estadía ofrece Villa San Vito?",
    "faq.2.a": "Es una villa privada en Raito para viajeros que prefieren terrazas, sombra de jardín, vistas al mar y una atmósfera local más lenta.",
    "faq.3.q": "¿Dónde está ubicada la villa?",
    "faq.3.a": "Villa San Vito está en Raito, sobre Vietri sul Mare, con vistas hacia el Golfo de Salerno y acceso a la Costa Amalfitana desde una base de pueblo más tranquila.",
    "faq.4.q": "¿Dónde encuentro los detalles prácticos?",
    "faq.4.a": "La capacidad, los servicios, las políticas, la disponibilidad y los detalles confirmados de reserva se mantienen en los anuncios de las plataformas externas.",
    "footer.reservations": "Las reservas se gestionan exclusivamente a través de Airbnb, Booking y Vrbo."
  },
  it: {
    skip: "Vai al contenuto",
    "nav.villa": "La Villa",
    "nav.story": "Storia",
    "nav.views": "Viste",
    "nav.location": "Posizione",
    "nav.book": "Prenota",
    "hero.eyebrow": "Raito, il segreto meglio custodito della Costiera Amalfitana",
    "hero.title": "Villa San Vito",
    "hero.subtitle": "Una villa privata con vista mare sopra Vietri sul Mare, dove la Costiera Amalfitana sembra più lenta, tranquilla e intima.",
    "buttons.discover": "Scopri la villa",
    "buttons.platforms": "Vedi le piattaforme",
    "buttons.airbnb": "Apri l'annuncio Airbnb",
    "buttons.booking": "Apri l'annuncio Booking",
    "buttons.vrbo": "Apri l'annuncio Vrbo",
    "trust.platforms": "Prenotazioni tramite piattaforme affidabili",
    "trust.private": "Villa privata, non hotel",
    "trust.sea": "Vista sul Golfo di Salerno",
    "facts.terraceLabel": "Terrazza",
    "facts.terrace": "Mattine all'aperto",
    "facts.gulfLabel": "Golfo",
    "facts.gulf": "Luce verso il mare",
    "facts.gardenLabel": "Giardino",
    "facts.garden": "Limone e ombra",
    "facts.raitoLabel": "Raito",
    "facts.raito": "Base di borgo quieto",
    "facts.homeLabel": "Casa",
    "facts.home": "Privata e vissuta",
    "facts.tableLabel": "Tavola",
    "facts.table": "Pasti senza fretta",
    "facts.parkingLabel": "Parking",
    "facts.parking": "Dentro la proprietà",
    "earlyPhotos.terrace": "La terrazza, il Golfo e la prima mattina senza fretta",
    "earlyPhotos.detail": "Piccoli dettagli, luce quieta",
    "earlyPhotos.sign": "Un ingresso privato a Raito",
    "story.kicker": "L'angolo perfetto per vivere la Costiera Amalfitana",
    "story.title": "Ci sono viaggi che riempiono la macchina fotografica.\nEd esperienze che fermano il tempo e ci ricordano che cosa conta davvero",
    "story.p1": "A Raito, la fretta resta sulle scogliere. Tutto, qui, invita alla serenità e al piacere.",
    "story.p2": "La Costiera Amalfitana non si visita soltanto: si sente.",
    "story.p3": "Villa San Vito è il rifugio ideale per scoprire il sud Italia a un altro ritmo. Un angolo di pura bellezza, dove la giornata si misura nel respiro della brezza in terrazza, nel tempo che impiega il caffè a raffreddarsi e nelle ore che il pomeriggio si prende prima di consegnarsi alla notte e alle sue stelle.",
    "story.p4": "A portata di Amalfi, Positano e Ravello, la villa unisce natura, privacy e viste che sembrano dipinte a mano. Tre livelli pensati per condividere, riposare e disconnettersi: interni generosi, giardini privati, terrazze indimenticabili e notti in cui il mare sembra fondersi con il silenzio.",
    "story.p5": "Qui le colazioni durano ore. Le conversazioni si allungano sotto le stelle. E ogni angolo invita a restare un giorno in più.",
    "story.p6": "Ideale per famiglie, gruppi di amici o viaggiatori che cercano più di un alloggio: un modo di vivere l'Italia dall'interno.",
    "story.signature": "Villa San Vito. La tua casa in Costiera Amalfitana.",
    "history.kicker": "Raito, memoria baciata dal sole",
    "history.title": "Un borgo sospeso tra montagna, mare e tempo",
    "history.caption": "Raito e Vietri in un dipinto del 1819 di Josef Rabel.",
    "history.p1": "Il nome Raito conserva un'antica suggestione di luce. Adagiato sopra Vietri sul Mare, il borgo si apre verso il Golfo di Salerno e vive tra roccia, limoni e il blu quieto della costa.",
    "history.p2": "Villa San Vito appartiene a questo paesaggio. Antica dimora dell'Ottocento, conserva l'atmosfera dell'architettura locale: pietra, terrazze, ombra, aria di mare e ambienti pensati per restare freschi nelle lunghe giornate mediterranee.",
    "history.p3": "La sua storia non è separata dal luogo che la circonda. Arrivare qui significa entrare nel ritmo più lento di Raito, dove la costa si guarda dall'alto e la luce della sera trasforma la villa in un piccolo balcone sul Golfo.",
    "slow.kicker": "Quiete mediterranea",
    "slow.title": "Un ritmo più lento sopra il Golfo di Salerno",
    "slow.copy": "Villa San Vito non ha nulla in comune con la routine levigata dei grandi hotel. La sua proposta appartiene alla calma e ai sensi, ai tempi del corpo e del cuore.",
    "seo.kicker": "Un soggiorno privato in Costiera Amalfitana",
    "seo.title": "Villa San Vito non è un hotel né un resort. È un'esperienza italiana.",
    "seo.copy": "Per chi sta scegliendo dove soggiornare in Costiera Amalfitana e confronta hotel, boutique stay, resort o case vacanza, Villa San Vito offre un'altra risposta: la privacy di una villa, ampi spazi interni ed esterni e la vista sul Golfo di Salerno. Non è all-inclusive e non è un hotel; è un soggiorno mediterraneo più personale per chi preferisce spazio, silenzio e un legame reale con la costa.",
    "compare.kicker": "Esperienza San Vito",
    "compare.title": "Un modo più lento di appartenere alla costa",
    "compare.card1.title": "Mattina in terrazza",
    "compare.card1.copy": "Caffè, aria di mare e il Golfo che si illumina lentamente sotto Raito.",
    "compare.card2.title": "Ombra in giardino",
    "compare.card2.copy": "Un albero di limoni, angoli quieti e spazio per sparire per un po'.",
    "compare.card3.title": "Pranzo senza orologio",
    "compare.card3.copy": "La cucina, la tavola e la terrazza fanno sentire un pasto semplice parte del paesaggio.",
    "compare.card4.title": "Sere sopra le luci",
    "compare.card4.copy": "Rientrare dalla costa in un borgo più calmo e guardare il Golfo diventare notte.",
    "compare.card5.title": "Una base con anima",
    "compare.card5.copy": "Privata, personale e radicata nell'architettura e nel ritmo del sud Italia.",
    "audience.kicker": "Per coppie, famiglie e amanti dello slow travel",
    "audience.title": "Una villa sul mare per un viaggio diverso",
    "audience.copy": "Villa San Vito è perfetta per coppie in cerca di una fuga romantica, amici che desiderano un soggiorno più lento sulla costa, e famiglie o piccoli gruppi che preferiscono un'esperienza di casa. Qui puoi vivere un po' più come un italiano: piano, tranquillo, guardando il mare tra i limoni, con buon cibo, aria aperta e un indimenticabile calice di vino.",
    "villa.kicker": "La villa",
    "villa.title": "Una casa da abitare lentamente",
    "villa.copy": "La villa è pensata per i rituali che contano sulla costa: svegliarsi con la luce, riunirsi intorno alla tavola, riposare negli interni freschi e tornare fuori ogni volta che il mare richiama l'attenzione.",
    "villa.caption": "Ombra del giardino, terrazze e quiete all'aperto.",
    "villa.moment1.label": "Fuori",
    "villa.moment1.title": "Terrazze, giardino e vista sul Golfo",
    "villa.moment1.copy": "Gli spazi esterni portano lo spirito della casa: aria aperta, foglie di limone, conversazioni lunghe e il mare sempre vicino.",
    "villa.moment2.label": "Dentro",
    "villa.moment2.title": "Ambienti freschi per riposare tra un'uscita e l'altra",
    "villa.moment2.copy": "Gli interni appaiono con discrezione, quanto basta per capire il comfort della proprietà senza trasformare il sito in un catalogo di stanze.",
    "villa.moment3.label": "Insieme",
    "villa.moment3.title": "Una tavola, una cucina e tempo da condividere",
    "villa.moment3.copy": "Villa San Vito funziona meglio quando le giornate si allungano: colazione fuori, pranzo dopo il mercato, vino mentre la costa si fa silenziosa.",
    "villa.practical": "I dettagli pratici su disposizione, capienza e servizi sono disponibili su Airbnb, Booking e Vrbo, dove si completano le prenotazioni.",
    "gallery.kicker": "Viste, texture e angoli quieti",
    "gallery.title": "Poche immagini per entrare nell'atmosfera",
    "gallery.note": "Una piccola selezione editoriale: terrazza, giardino, tavola, maioliche e dettagli. Gli interni compaiono solo come orientamento, non come catalogo.",
    "gallery.item1": "Terrazza del giardino",
    "gallery.item2": "Terrazza sul Golfo",
    "gallery.item3": "Tavola per pasti senza fretta",
    "gallery.item4": "Maioliche della cucina",
    "gallery.item5": "Limone sopra il Golfo",
    "gallery.item6": "Arco azzurro e luce sulle scale",
    "location.kicker": "Posizione",
    "location.title": "Raito, sopra Vietri sul Mare",
    "location.copy": "Raito è un borgo tranquillo sopra Vietri sul Mare, conosciuto per le sue viste, l'atmosfera calma e la vicinanza a Salerno. Da qui gli ospiti possono esplorare la Costiera Amalfitana e rientrare a fine giornata in una base privata e serena.",
    "location.note": "Il sito mostra l'area generale. I dettagli esatti dell'indirizzo possono essere gestiti tramite la piattaforma di prenotazione.",
    "nearby.kicker": "Esplora la costa",
    "nearby.title": "La base perfetta per esplorare il meglio della Costiera Amalfitana",
    "nearby.intro": "Da Villa San Vito puoi visitare in giornata alcuni dei luoghi più belli della zona.",
    "nearby.vietri": "Un vicino borgo costiero noto per le ceramiche, la vista mare e il carattere locale.",
    "nearby.salerno": "Un punto d'appoggio pratico per trasporti, ristoranti e passeggiate sul lungomare vicino alla Costiera Amalfitana.",
    "nearby.amalfi": "Una tappa classica della Costiera Amalfitana e una bella gita dalla villa.",
    "nearby.ravello": "Un raffinato borgo collinare amato per giardini, viste e patrimonio culturale.",
    "nearby.positano": "Un celebre borgo verticale sul mare, raggiungibile come parte di un itinerario costiero.",
    "nearby.pompeii": "Un sito archeologico essenziale per chi ama la storia romana.",
    "nearby.paestum": "Una gita appagante tra templi greci, archeologia e paesaggi aperti.",
    "booking.kicker": "Prenotazioni",
    "booking.title": "Quando sei pronto, scegli la tua piattaforma",
    "booking.copy": "Questo sito è un'introduzione calma alla villa. Disponibilità, pagamenti, politiche e prenotazioni sono gestiti esternamente da Airbnb, Booking e Vrbo.",
    "booking.airbnb.copy": "Consulta l'annuncio, le note degli ospiti e i dettagli di prenotazione.",
    "booking.booking.copy": "Verifica disponibilità, politiche e informazioni per viaggiatori.",
    "booking.vrbo.copy": "Consulta la pagina Vrbo e i dettagli di prenotazione.",
    "booking.disclaimer": "Questo sito è una vetrina informativa per Villa San Vito. Le prenotazioni dirette non vengono elaborate qui.",
    "reviews.kicker": "Recensioni verificate",
    "reviews.title": "Ciò che resta agli ospiti",
    "reviews.label": "Nota degli ospiti",
    "reviews.airbnb": "Verificato su Airbnb",
    "reviews.count": "14 recensioni verificate",
    "reviews.highlights": "Il ricordo che ritorna è semplice: la vista, gli spazi esterni, la posizione tranquilla e la facilità di rientrare in una vera casa dopo la costa.",
    "reviews.placeholder": "È un posto molto buono. Vista spettacolare da un enorme patio sul retro. L'alloggio era in buone condizioni. Molto consigliato. Il parcheggio è un po' stretto, ma ce lo avevano comunicato bene, quindi non ci sono state sorprese.",
    "reviews.link": "Leggi le recensioni su Airbnb",
    "reviews.note": "La cronologia completa delle recensioni e i dettagli delle piattaforme sono disponibili negli annunci di prenotazione.",
    "faq.kicker": "Prima di prenotare",
    "faq.title": "Domande frequenti",
    "faq.1.q": "Posso prenotare direttamente su questo sito?",
    "faq.1.a": "No. Questo sito è solo una presentazione editoriale di Villa San Vito. Le prenotazioni si completano tramite Airbnb, Booking o Vrbo.",
    "faq.2.q": "Che tipo di soggiorno offre Villa San Vito?",
    "faq.2.a": "È una villa privata a Raito per viaggiatori che preferiscono terrazze, ombra del giardino, vista mare e un'atmosfera locale più lenta.",
    "faq.3.q": "Dove si trova la villa?",
    "faq.3.a": "Villa San Vito si trova a Raito, sopra Vietri sul Mare, con vista verso il Golfo di Salerno e accesso alla Costiera Amalfitana da una base di borgo più tranquilla.",
    "faq.4.q": "Dove trovo i dettagli pratici?",
    "faq.4.a": "Capienza, servizi, politiche, disponibilità e dettagli confermati di prenotazione sono mantenuti negli annunci delle piattaforme esterne.",
    "footer.reservations": "Le prenotazioni sono gestite esclusivamente tramite Airbnb, Booking e Vrbo."
  }
};

const header = document.querySelector(".site-header");
const languageButtons = document.querySelectorAll("[data-lang]");
const translatableNodes = document.querySelectorAll("[data-i18n]");
const galleryDialog = document.querySelector(".gallery-dialog");
const galleryDialogImage = galleryDialog?.querySelector("img");
const galleryDialogCaption = galleryDialog?.querySelector("p");
const galleryClose = galleryDialog?.querySelector(".dialog-close");

function setLanguage(language) {
  const selectedLanguage = translations[language] ? language : "en";
  document.documentElement.lang = selectedLanguage;

  translatableNodes.forEach((node) => {
    const key = node.dataset.i18n;
    const value = translations[selectedLanguage][key];
    if (value) {
      node.textContent = value;
    }
  });

  languageButtons.forEach((button) => {
    const isActive = button.dataset.lang === selectedLanguage;
    button.classList.toggle("is-active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("villaSanVitoLanguage", selectedLanguage);
}

function updateHeaderState() {
  header?.classList.toggle("is-scrolled", window.scrollY > 24);
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

document.querySelectorAll(".gallery-item").forEach((item) => {
  item.addEventListener("click", () => {
    if (!galleryDialog || !galleryDialogImage || !galleryDialogCaption) {
      return;
    }

    const image = item.querySelector("img");
    const caption = item.querySelector("span")?.textContent || image?.alt || "";
    galleryDialogImage.src = item.dataset.full || image?.src || "";
    galleryDialogImage.alt = image?.alt || caption;
    galleryDialogCaption.textContent = caption;
    galleryDialog.showModal();
  });
});

galleryClose?.addEventListener("click", () => galleryDialog?.close());

galleryDialog?.addEventListener("click", (event) => {
  if (event.target === galleryDialog) {
    galleryDialog.close();
  }
});

window.addEventListener("scroll", updateHeaderState, { passive: true });
updateHeaderState();

setLanguage(localStorage.getItem("villaSanVitoLanguage") || "en");
