// EDIT TEXTS: update static multilingual copy here. Keep keys aligned with data-i18n attributes in index.html.
const translations = {
  en: {
    skip: "Skip to content",
    "nav.villa": "The Villa",
    "nav.story": "Story",
    "nav.views": "Views",
    "nav.location": "Location",
    "nav.book": "Book",
    "hero.eyebrow": "Raito, Amalfi Coast",
    "hero.title": "Villa San Vito",
    "hero.subtitle": "A private sea-view villa above Vietri sul Mare, where the Amalfi Coast feels slower, quieter and more intimate.",
    "buttons.discover": "Discover the villa",
    "buttons.airbnb": "Book on Airbnb",
    "buttons.booking": "Book on Booking",
    "buttons.vrbo": "Book on Vrbo",
    "trust.platforms": "Reservations through trusted platforms",
    "trust.private": "Private villa, not a hotel",
    "trust.sea": "Sea views over the Gulf of Salerno",
    "facts.guests": "Up to 6 guests",
    "facts.bedrooms": "3 bedrooms",
    "facts.beds": "5 beds",
    "facts.bathrooms": "3 bathrooms",
    "facts.gardenLabel": "Garden",
    "facts.garden": "Private garden",
    "facts.wifi": "Fast WiFi",
    "facts.parkingLabel": "Parking",
    "facts.parking": "Private parking",
    "earlyPhotos.terrace": "The terrace, the Gulf and the first slow morning",
    "earlyPhotos.sign": "A private entrance in Raito",
    "earlyPhotos.coast": "Vietri sul Mare and the coast nearby",
    "story.kicker": "The perfect corner to enjoy the Amalfi Coast",
    "story.title": "Some trips fill the camera roll. Others slow time down and remind us what life is about.",
    "story.p1": "The rush stays on the cliffs.",
    "story.p2": "Here begins the Amalfi Coast you can actually feel.",
    "story.p3": "Welcome to Villa San Vito, a refuge designed for discovering southern Italy at another rhythm. Here, the day is measured in terrace breeze, unhurried coffee and the quiet only this hidden corner can offer.",
    "story.p4": "Just within reach of Amalfi, Positano and Ravello, the villa brings together nature, privacy and hand-painted views. Three levels designed for sharing, resting and disconnecting: generous interiors, private gardens, unforgettable terraces and nights when the sea seems to blend with the silence.",
    "story.p5": "Here, breakfasts last for hours. Conversations stretch beneath the stars. And every corner invites you to stay one more day.",
    "story.p6": "Ideal for families, groups of friends or travelers looking for more than accommodation: a way to live Italy from within.",
    "story.signature": "Villa San Vito. Your home on the Amalfi Coast.",
    "slow.kicker": "Mediterranean stillness",
    "slow.title": "A slower rhythm above the Gulf of Salerno",
    "slow.copy": "This is not the polished routine of a large Amalfi Coast resort. It is the quiet of a private garden, the shade of lemon leaves, the comfort of a kitchen, and terraces where the day can unfold without hurry.",
    "seo.kicker": "A private stay on the Amalfi Coast",
    "seo.title": "Villa San Vito is not a hotel or a resort. It is an Italian coastal experience.",
    "seo.copy": "For travelers wondering where to stay on the Amalfi Coast and comparing hotels, boutique stays, resorts or vacation rentals, Villa San Vito offers a different answer: the privacy of a private villa, generous indoor and outdoor spaces, and sea views over the Gulf of Salerno. It is not all-inclusive and it is not a hotel; it is a more personal Mediterranean stay for those who prefer space, silence and a real connection with the coast.",
    "compare.kicker": "The Villa San Vito experience",
    "compare.title": "A stay designed for intimacy and enjoyment",
    "compare.copy": "Villa San Vito is for travelers who want privacy without feeling isolated, comfort without formality, and a base that makes the coast feel personal. It is a calm, sea-view home for days shaped by terraces, garden light and time together.",
    "compare.card1.title": "More privacy than a hotel room",
    "compare.card1.copy": "The villa is yours to inhabit, from breakfast on the terrace to quiet evenings in the garden.",
    "compare.card2.title": "More space for families and friends",
    "compare.card2.copy": "Three bedrooms, generous interiors and outdoor areas make it easy to share time without feeling crowded.",
    "compare.card3.title": "A quieter base near iconic towns",
    "compare.card3.copy": "Return to Raito after exploring Amalfi, Ravello, Positano, Vietri sul Mare and Salerno.",
    "compare.card4.title": "A villa with sea views and garden terraces",
    "compare.card4.copy": "A serene alternative to large Amalfi Coast hotels, with outdoor spaces and some of the best views over the Gulf.",
    "compare.card5.title": "A local feeling away from the busiest areas",
    "compare.card5.copy": "Stay above Vietri sul Mare and experience the coast from a more intimate village setting.",
    "audience.kicker": "For couples, families and slow-travel lovers",
    "audience.title": "A coastal villa for a different kind of trip",
    "audience.copy": "Villa San Vito is perfect for couples looking for a romantic escape, friends planning a slower coastal stay, and families or small groups who want a homelike experience. Here, you can live a little more like an Italian: slowly, quietly, looking at the sea through lemon trees, with good food, open air and an unforgettable glass of wine.",
    "villa.kicker": "The villa",
    "villa.title": "One home, three spaces: a level for every need",
    "villa.copy": "Villa San Vito unfolds across three levels, each designed for a different part of the stay: open social spaces, quiet bedrooms and terraces made for slow coastal moments.",
    "villa.stat.levels": "levels",
    "villa.stat.bedrooms": "bedrooms",
    "villa.stat.beds": "beds",
    "villa.stat.bathrooms": "bathrooms",
    "villa.stat.viewsLabel": "Sea",
    "villa.stat.views": "Gulf views",
    "villa.stat.gardenLabel": "Garden",
    "villa.stat.garden": "private outdoor space",
    "villa.stat.wifi": "fast connection",
    "villa.stat.parkingLabel": "Parking",
    "villa.stat.parking": "inside the property",
    "villa.ground.title": "Ground floor",
    "villa.ground.copy": "A spacious living room, fully equipped kitchen and dining area open toward the furnished terrace and private garden. An outdoor bathroom adds convenience for time spent outside.",
    "villa.first.title": "First floor",
    "villa.first.copy": "A work and study area sits alongside two bedrooms with single beds, a full bathroom and a separate shower, giving guests flexibility and quiet corners.",
    "villa.second.title": "Second floor",
    "villa.second.copy": "The main bedroom has a double bed, a bathroom with bathtub and a large terrace overlooking the Gulf of Salerno.",
    "villa.outdoor.title": "Outdoor areas",
    "villa.outdoor.copy": "The private garden, lemon tree, furnished terraces and sea-facing views create the calm outdoor living that defines the property.",
    "gallery.kicker": "Views and interiors",
    "gallery.title": "Mediterranean light, garden terraces and generous interiors",
    "gallery.note": "Selected scenes from the terraces, garden, interiors and coastal setting.",
    "gallery.item1": "Terrace and sea view",
    "gallery.item2": "Private garden",
    "gallery.item3": "Lemon tree",
    "gallery.item4": "Kitchen",
    "gallery.item5": "Dining details",
    "gallery.item6": "Table setting",
    "gallery.item7": "Main bedroom",
    "gallery.item8": "Single bedrooms",
    "gallery.item9": "Interior arch",
    "gallery.item10": "Living room",
    "gallery.item11": "Sitting room",
    "location.kicker": "Location",
    "location.title": "Raito, above Vietri sul Mare",
    "location.copy": "Raito is a quiet village above Vietri sul Mare, known for its views, calm atmosphere and proximity to Salerno. From here, guests can explore the Amalfi Coast while returning to a private and peaceful home base at the end of the day.",
    "location.note": "The website shows the general area. Exact address details can be managed through the booking platform.",
    "nearby.kicker": "Explore the coast",
    "nearby.title": "The perfect base for exploring the best of the Amalfi Coast",
    "nearby.intro": "From Villa San Vito, you can spend the day discovering some of the most beautiful places in the area.",
    "nearby.vietri": "A nearby coastal town known for ceramics, sea views and relaxed local character.",
    "nearby.salerno": "A practical gateway for transport, dining and waterfront walks near the Amalfi Coast.",
    "nearby.amalfi": "A classic Amalfi Coast stop and a beautiful day trip from the villa.",
    "nearby.ravello": "A refined hill town loved for gardens, views and cultural heritage.",
    "nearby.positano": "A famous vertical seaside village reachable as part of a coastal itinerary.",
    "nearby.pompeii": "An essential archaeological site for travelers interested in Roman history.",
    "nearby.paestum": "A rewarding day trip for Greek temples, archaeology and open landscapes.",
    "booking.kicker": "Reservations",
    "booking.title": "Book Villa San Vito through your preferred platform",
    "booking.copy": "Reservations, payments, availability and cancellation policies are managed directly by Airbnb, Booking and Vrbo. Choose the platform you prefer and complete your reservation securely there.",
    "booking.airbnb.copy": "View the Airbnb listing, reviews and reservation details.",
    "booking.booking.copy": "Compare Booking availability, policies and traveler information.",
    "booking.vrbo.copy": "View the Vrbo listing and booking details.",
    "booking.disclaimer": "This website is an informational showcase for Villa San Vito. Direct bookings are not processed here.",
    "reviews.kicker": "Verified reviews",
    "reviews.title": "What guests say after living the Villa San Vito experience",
    "reviews.airbnb": "Airbnb rating",
    "reviews.count": "14 reviews",
    "reviews.highlights": "Highlights guests mention: views, hospitality, location, parking, outdoor spaces and comfort.",
    "reviews.placeholder": "This is a very good place. Spectacular view from a huge backyard. The accommodation was in good condition. Highly recommended. The parking is a little narrow, but we were properly informed about that, so there were no surprises.",
    "reviews.link": "Read reviews on Airbnb",
    "reviews.note": "Full review history and platform details are available on the reservation listings.",
    "faq.kicker": "Before you book",
    "faq.title": "Frequently asked questions",
    "faq.1.q": "Is Villa San Vito one of the best places to stay in Amalfi Coast?",
    "faq.1.a": "Villa San Vito is a private vacation rental in Raito, ideal for travelers wondering where to stay in Amalfi Coast and looking for sea views, privacy and more space than a traditional hotel room.",
    "faq.2.q": "Is Villa San Vito a hotel or a private villa?",
    "faq.2.a": "Villa San Vito is not a hotel. It is a private villa Amalfi Coast rental available through Airbnb, Booking and Vrbo.",
    "faq.3.q": "Is this a good alternative to luxury hotels in Amalfi Coast Italy?",
    "faq.3.a": "Yes, for travelers who prefer privacy, terraces, a garden and a local atmosphere instead of hotel services, Villa San Vito can be a strong alternative to luxury hotels Amalfi Coast Italy.",
    "faq.4.q": "Is Villa San Vito suitable for families?",
    "faq.4.a": "Yes. Families comparing family hotels Amalfi Coast may appreciate the villa’s three bedrooms, full kitchen, parking, outdoor areas and space for up to six guests.",
    "faq.5.q": "Is Villa San Vito good for couples?",
    "faq.5.a": "Yes. Couples looking for an Italian coastal villa for couples or an alternative to Amalfi Coast honeymoon hotels may enjoy the quiet terraces, sea views and private setting.",
    "faq.6.q": "Is Villa San Vito beachfront?",
    "faq.6.a": "Villa San Vito is not described as a beachfront hotel. It is a sea-view villa in Raito, above Vietri sul Mare, with views toward the Gulf of Salerno.",
    "faq.7.q": "Is Villa San Vito all inclusive?",
    "faq.7.a": "No. Villa San Vito is not an all inclusive Amalfi Coast resort. It is a private vacation rental with kitchen, garden, terraces and booking through external platforms.",
    "faq.8.q": "Can I book directly on this website?",
    "faq.8.a": "No. All reservations are completed through Airbnb, Booking or Vrbo.",
    "footer.reservations": "Reservations are managed exclusively through Airbnb, Booking and Vrbo."
  },
  es: {
    skip: "Saltar al contenido",
    "nav.villa": "La Villa",
    "nav.story": "Historia",
    "nav.views": "Vistas",
    "nav.location": "Ubicación",
    "nav.book": "Reservar",
    "hero.eyebrow": "Raito, Costa Amalfitana",
    "hero.title": "Villa San Vito",
    "hero.subtitle": "Una villa privada con vista al mar sobre Vietri sul Mare, donde la Costa Amalfitana se siente más lenta, tranquila e íntima.",
    "buttons.discover": "Descubrir la villa",
    "buttons.airbnb": "Reservar en Airbnb",
    "buttons.booking": "Reservar en Booking",
    "buttons.vrbo": "Reservar en Vrbo",
    "trust.platforms": "Reservas a través de plataformas confiables",
    "trust.private": "Villa privada, no hotel",
    "trust.sea": "Vistas al Golfo de Salerno",
    "facts.guests": "Hasta 6 huéspedes",
    "facts.bedrooms": "3 dormitorios",
    "facts.beds": "5 camas",
    "facts.bathrooms": "3 baños",
    "facts.gardenLabel": "Jardín",
    "facts.garden": "Jardín privado",
    "facts.wifi": "WiFi rápido",
    "facts.parkingLabel": "Parking",
    "facts.parking": "Estacionamiento privado",
    "earlyPhotos.terrace": "La terraza, el Golfo y la primera mañana sin apuro",
    "earlyPhotos.sign": "Una entrada privada en Raito",
    "earlyPhotos.coast": "Vietri sul Mare y la costa cercana",
    "story.kicker": "El rincón perfecto para disfrutar la Costa Amalfitana",
    "story.title": "Hay viajes que llenan la cámara de fotos. Y otros que detienen el tiempo y nos recuerdan de qué se trata la vida.",
    "story.p1": "La prisa se queda en los acantilados.",
    "story.p2": "Aquí empieza la Costa Amalfitana que se siente.",
    "story.p3": "Bienvenido a Villa San Vito, un refugio diseñado para descubrir el sur de Italia a otro ritmo. Aquí, el día se mide en la brisa de la terraza, el café sin prisas y el silencio que solo este rincón secreto puede ofrecer.",
    "story.p4": "A pocos minutos de Amalfi, Positano y Ravello, la villa combina naturaleza, privacidad y vistas que parecen pintadas a mano. Tres niveles diseñados para compartir, descansar y desconectarse: interiores amplios, jardines privados, terrazas inolvidables y noches en las que el mar parece mezclarse con el silencio.",
    "story.p5": "Acá los desayunos duran horas. Las charlas se alargan bajo las estrellas. Y cada rincón invita a quedarse un día más.",
    "story.p6": "Ideal para familias, grupos de amigos o viajeros que buscan algo más que hospedarse: vivir Italia desde adentro.",
    "story.signature": "Villa San Vito. Tu casa en la Costa Amalfitana.",
    "slow.kicker": "Quietud mediterránea",
    "slow.title": "Un ritmo más lento sobre el Golfo de Salerno",
    "slow.copy": "Esto no es la rutina pulida de un gran resort en la Costa Amalfitana. Es la calma de un jardín privado, la sombra de los limoneros, la comodidad de una cocina y terrazas donde el día puede desplegarse sin apuro.",
    "seo.kicker": "Una estadía privada en la Costa Amalfitana",
    "seo.title": "Villa San Vito no es un hotel, ni un resort. Es una experiencia italiana.",
    "seo.copy": "Para viajeros que están decidiendo dónde alojarse en la Costa Amalfitana y comparan hoteles, alojamientos boutique, resorts o alquileres vacacionales, Villa San Vito ofrece otra respuesta: la privacidad de una villa, espacios interiores y exteriores amplios, y vistas al Golfo de Salerno. No es todo incluido y no es un hotel; es una estadía mediterránea más personal para quienes prefieren espacio, silencio y una conexión real con la costa.",
    "compare.kicker": "Experiencia San Vito",
    "compare.title": "Un hospedaje diseñado para la intimidad y el disfrute",
    "compare.copy": "Villa San Vito es para viajeros que quieren privacidad sin sentirse aislados, comodidad sin formalidad y una base que haga que la costa se sienta personal. Es una casa serena con vista al mar para días marcados por terrazas, luz de jardín y tiempo compartido.",
    "compare.card1.title": "Más privacidad que una habitación de hotel",
    "compare.card1.copy": "La villa es tuya para habitarla, desde el desayuno en la terraza hasta las noches tranquilas en el jardín.",
    "compare.card2.title": "Más espacio para familias y amigos",
    "compare.card2.copy": "Tres dormitorios, interiores amplios y zonas exteriores hacen fácil compartir sin sentirse apretados.",
    "compare.card3.title": "Una base tranquila cerca de pueblos icónicos",
    "compare.card3.copy": "Vuelve a Raito después de explorar Amalfi, Ravello, Positano, Vietri sul Mare y Salerno.",
    "compare.card4.title": "Una villa con vista al mar y terrazas con jardines",
    "compare.card4.copy": "La alternativa serena a los hoteles masivos de la Costa Amalfitana, con espacios exteriores y las mejores vistas al Golfo.",
    "compare.card5.title": "Una sensación local lejos de las zonas más concurridas",
    "compare.card5.copy": "Alójate sobre Vietri sul Mare y vive la costa desde un pueblo más íntimo.",
    "audience.kicker": "Para parejas, familias y amantes del slow travel",
    "audience.title": "Una villa costera para un viaje diferente",
    "audience.copy": "Villa San Vito es perfecta para parejas que buscan una escapada romántica, amigos que quieren una estadía más lenta junto a la costa, y familias o grupos pequeños que prefieren una experiencia hogareña. Aquí puedes vivir como un italiano más: despacio, tranquilo, mirando el mar entre limoneros, con buena comida, aire libre y una inolvidable copa de vino.",
    "villa.kicker": "La villa",
    "villa.title": "Un hogar, tres espacios: un nivel para cada necesidad",
    "villa.copy": "Villa San Vito distribuye sus encantos en tres niveles. Cada piso está diseñado para ofrecer una experiencia distinta: áreas sociales abiertas, dormitorios tranquilos y terrazas pensadas para disfrutar la Costa Amalfitana sin apuro.",
    "villa.stat.levels": "niveles",
    "villa.stat.bedrooms": "dormitorios",
    "villa.stat.beds": "camas",
    "villa.stat.bathrooms": "baños",
    "villa.stat.viewsLabel": "Mar",
    "villa.stat.views": "vistas al Golfo",
    "villa.stat.gardenLabel": "Jardín",
    "villa.stat.garden": "espacio exterior privado",
    "villa.stat.wifi": "conexión rápida",
    "villa.stat.parkingLabel": "Parking",
    "villa.stat.parking": "dentro de la propiedad",
    "villa.ground.title": "Planta baja",
    "villa.ground.copy": "Un living amplio, cocina equipada y comedor se abren hacia la terraza amueblada y el jardín privado. El baño exterior suma comodidad para disfrutar los espacios al aire libre.",
    "villa.first.title": "Primer piso",
    "villa.first.copy": "Una zona de trabajo y estudio acompaña dos dormitorios con camas individuales, un baño completo y una ducha separada, ofreciendo flexibilidad y rincones tranquilos.",
    "villa.second.title": "Segundo piso",
    "villa.second.copy": "El dormitorio principal cuenta con cama doble, baño con bañera y una gran terraza con vista al Golfo de Salerno.",
    "villa.outdoor.title": "Áreas exteriores",
    "villa.outdoor.copy": "El jardín privado, el limonero, las terrazas amuebladas y las vistas al mar definen la vida al aire libre de la propiedad.",
    "gallery.kicker": "Vistas e interiores",
    "gallery.title": "Luz mediterránea, terrazas con jardín e interiores amplios",
    "gallery.note": "Escenas seleccionadas de las terrazas, el jardín, los interiores y el entorno costero.",
    "gallery.item1": "Terraza y vista al mar",
    "gallery.item2": "Jardín privado",
    "gallery.item3": "Limonero",
    "gallery.item4": "Cocina",
    "gallery.item5": "Detalles del comedor",
    "gallery.item6": "Mesa preparada",
    "gallery.item7": "Dormitorio principal",
    "gallery.item8": "Dormitorios individuales",
    "gallery.item9": "Arco interior",
    "gallery.item10": "Living",
    "gallery.item11": "Sala de estar",
    "location.kicker": "Ubicación",
    "location.title": "Raito, sobre Vietri sul Mare",
    "location.copy": "Raito es un pueblo tranquilo sobre Vietri sul Mare, conocido por sus vistas, su calma y su cercanía a Salerno. Desde aquí, los huéspedes pueden explorar la Costa Amalfitana y volver al final del día a una base privada y serena.",
    "location.note": "El sitio muestra la zona general. Los detalles exactos de dirección pueden gestionarse desde la plataforma de reserva.",
    "nearby.kicker": "Explorar la costa",
    "nearby.title": "La base perfecta para recorrer lo mejor de la Costa Amalfitana",
    "nearby.intro": "Desde Villa San Vito, puedes visitar en el día los lugares más bellos de la zona.",
    "nearby.vietri": "Un pueblo costero cercano, reconocido por sus cerámicas, vistas al mar y carácter local.",
    "nearby.salerno": "Una base práctica para transporte, gastronomía y paseos junto al mar cerca de la Costa Amalfitana.",
    "nearby.amalfi": "Una parada clásica de la Costa Amalfitana y una hermosa excursión desde la villa.",
    "nearby.ravello": "Un pueblo de altura refinado, famoso por jardines, vistas y patrimonio cultural.",
    "nearby.positano": "Un célebre pueblo vertical junto al mar, alcanzable dentro de un itinerario costero.",
    "nearby.pompeii": "Un sitio arqueológico esencial para viajeros interesados en la historia romana.",
    "nearby.paestum": "Una excursión valiosa para ver templos griegos, arqueología y paisajes abiertos.",
    "booking.kicker": "Reservas",
    "booking.title": "Reserva Villa San Vito en tu plataforma preferida",
    "booking.copy": "Las reservas, pagos, disponibilidad y políticas de cancelación son gestionadas directamente por Airbnb, Booking y Vrbo. Elige la plataforma que prefieras y completa tu reserva de forma segura allí.",
    "booking.airbnb.copy": "Ver el anuncio de Airbnb, reseñas y detalles de reserva.",
    "booking.booking.copy": "Comparar disponibilidad, políticas e información para viajeros en Booking.",
    "booking.vrbo.copy": "Ver el anuncio de Vrbo y los detalles de reserva.",
    "booking.disclaimer": "Este sitio web es una vidriera informativa de Villa San Vito. Aquí no se procesan reservas directas.",
    "reviews.kicker": "Reseñas verificadas",
    "reviews.title": "Qué dicen sobre Villa San Vito quienes vivieron la experiencia",
    "reviews.airbnb": "Rating en Airbnb",
    "reviews.count": "14 reseñas",
    "reviews.highlights": "Aspectos que mencionan los huéspedes: vistas, hospitalidad, ubicación, estacionamiento, espacios exteriores y confort.",
    "reviews.placeholder": "Este es un muy buen lugar. Vista espectacular desde un patio trasero enorme. El alojamiento estaba en buenas condiciones. Muy recomendable. El estacionamiento es un poco estrecho, pero nos avisaron bien de eso. Así que no hubo sorpresas.",
    "reviews.link": "Ver reseñas en Airbnb",
    "reviews.note": "El historial completo de reseñas y los detalles de cada plataforma están disponibles en los anuncios de reserva.",
    "faq.kicker": "Antes de reservar",
    "faq.title": "Preguntas frecuentes",
    "faq.1.q": "¿Villa San Vito es uno de los mejores lugares para alojarse en la Costa Amalfitana?",
    "faq.1.a": "Villa San Vito es un alquiler vacacional privado en Raito, ideal para viajeros que se preguntan dónde alojarse en la Costa Amalfitana y buscan vistas al mar, privacidad y más espacio que una habitación de hotel tradicional.",
    "faq.2.q": "¿Villa San Vito es un hotel o una villa privada?",
    "faq.2.a": "Villa San Vito no es un hotel. Es una villa privada en la Costa Amalfitana disponible a través de Airbnb, Booking y Vrbo.",
    "faq.3.q": "¿Es una buena alternativa a hoteles de lujo en la Costa Amalfitana?",
    "faq.3.a": "Sí, para viajeros que prefieren privacidad, terrazas, jardín y una atmósfera local en lugar de servicios hoteleros, Villa San Vito puede ser una gran alternativa a hoteles de lujo en la Costa Amalfitana.",
    "faq.4.q": "¿Villa San Vito es adecuada para familias?",
    "faq.4.a": "Sí. Las familias que comparan hoteles familiares en la Costa Amalfitana pueden valorar sus tres dormitorios, cocina completa, estacionamiento, espacios exteriores y capacidad para hasta seis huéspedes.",
    "faq.5.q": "¿Villa San Vito es buena para parejas?",
    "faq.5.a": "Sí. Las parejas que buscan una villa costera italiana o una alternativa a los hoteles de luna de miel en la Costa Amalfitana pueden disfrutar sus terrazas tranquilas, vistas al mar y entorno privado.",
    "faq.6.q": "¿Villa San Vito está frente a la playa?",
    "faq.6.a": "Villa San Vito no se describe como un hotel frente a la playa. Es una villa con vista al mar en Raito, sobre Vietri sul Mare, con vistas hacia el Golfo de Salerno.",
    "faq.7.q": "¿Villa San Vito es all inclusive?",
    "faq.7.a": "No. Villa San Vito no es un resort todo incluido en la Costa Amalfitana. Es un alquiler vacacional privado con cocina, jardín, terrazas y reserva a través de plataformas externas.",
    "faq.8.q": "¿Puedo reservar directamente en este sitio?",
    "faq.8.a": "No. Todas las reservas se completan a través de Airbnb, Booking o Vrbo.",
    "footer.reservations": "Las reservas se gestionan exclusivamente a través de Airbnb, Booking y Vrbo."
  },
  it: {
    skip: "Vai al contenuto",
    "nav.villa": "La Villa",
    "nav.story": "Storia",
    "nav.views": "Viste",
    "nav.location": "Posizione",
    "nav.book": "Prenota",
    "hero.eyebrow": "Raito, Costiera Amalfitana",
    "hero.title": "Villa San Vito",
    "hero.subtitle": "Una villa privata con vista mare sopra Vietri sul Mare, dove la Costiera Amalfitana sembra più lenta, tranquilla e intima.",
    "buttons.discover": "Scopri la villa",
    "buttons.airbnb": "Prenota su Airbnb",
    "buttons.booking": "Prenota su Booking",
    "buttons.vrbo": "Prenota su Vrbo",
    "trust.platforms": "Prenotazioni tramite piattaforme affidabili",
    "trust.private": "Villa privata, non hotel",
    "trust.sea": "Vista sul Golfo di Salerno",
    "facts.guests": "Fino a 6 ospiti",
    "facts.bedrooms": "3 camere",
    "facts.beds": "5 letti",
    "facts.bathrooms": "3 bagni",
    "facts.gardenLabel": "Giardino",
    "facts.garden": "Giardino privato",
    "facts.wifi": "WiFi veloce",
    "facts.parkingLabel": "Parking",
    "facts.parking": "Parcheggio privato",
    "earlyPhotos.terrace": "La terrazza, il Golfo e la prima mattina senza fretta",
    "earlyPhotos.sign": "Un ingresso privato a Raito",
    "earlyPhotos.coast": "Vietri sul Mare e la costa vicina",
    "story.kicker": "L'angolo perfetto per vivere la Costiera Amalfitana",
    "story.title": "Ci sono viaggi che riempiono la macchina fotografica. E altri che fermano il tempo e ci ricordano che cosa conta davvero.",
    "story.p1": "La fretta resta sulle scogliere.",
    "story.p2": "Qui comincia la Costiera Amalfitana che si sente davvero.",
    "story.p3": "Benvenuto a Villa San Vito, un rifugio pensato per scoprire il sud Italia a un altro ritmo. Qui la giornata si misura nella brezza della terrazza, nel caffè senza fretta e nel silenzio che solo questo angolo nascosto può offrire.",
    "story.p4": "A portata di Amalfi, Positano e Ravello, la villa unisce natura, privacy e viste che sembrano dipinte a mano. Tre livelli pensati per condividere, riposare e disconnettersi: interni generosi, giardini privati, terrazze indimenticabili e notti in cui il mare sembra fondersi con il silenzio.",
    "story.p5": "Qui le colazioni durano ore. Le conversazioni si allungano sotto le stelle. E ogni angolo invita a restare un giorno in più.",
    "story.p6": "Ideale per famiglie, gruppi di amici o viaggiatori che cercano più di un alloggio: un modo di vivere l'Italia dall'interno.",
    "story.signature": "Villa San Vito. La tua casa in Costiera Amalfitana.",
    "slow.kicker": "Quiete mediterranea",
    "slow.title": "Un ritmo più lento sopra il Golfo di Salerno",
    "slow.copy": "Non è la routine levigata di un grande resort in Costiera Amalfitana. È la calma di un giardino privato, l'ombra delle foglie di limone, il comfort di una cucina e terrazze dove la giornata può scorrere senza fretta.",
    "seo.kicker": "Un soggiorno privato in Costiera Amalfitana",
    "seo.title": "Villa San Vito non è un hotel né un resort. È un'esperienza italiana.",
    "seo.copy": "Per chi sta scegliendo dove soggiornare in Costiera Amalfitana e confronta hotel, boutique stay, resort o case vacanza, Villa San Vito offre un'altra risposta: la privacy di una villa, ampi spazi interni ed esterni e la vista sul Golfo di Salerno. Non è all-inclusive e non è un hotel; è un soggiorno mediterraneo più personale per chi preferisce spazio, silenzio e un legame reale con la costa.",
    "compare.kicker": "Esperienza San Vito",
    "compare.title": "Un soggiorno pensato per l'intimità e il piacere",
    "compare.copy": "Villa San Vito è per viaggiatori che desiderano privacy senza sentirsi isolati, comfort senza formalità e una base che renda la costa più personale. È una casa serena con vista mare, per giornate scandite da terrazze, luce del giardino e tempo condiviso.",
    "compare.card1.title": "Più privacy di una camera d'hotel",
    "compare.card1.copy": "La villa è tua da vivere, dalla colazione in terrazza alle serate tranquille in giardino.",
    "compare.card2.title": "Più spazio per famiglie e amici",
    "compare.card2.copy": "Tre camere, interni generosi e spazi esterni rendono facile condividere senza sentirsi stretti.",
    "compare.card3.title": "Una base tranquilla vicino ai luoghi iconici",
    "compare.card3.copy": "Rientra a Raito dopo aver esplorato Amalfi, Ravello, Positano, Vietri sul Mare e Salerno.",
    "compare.card4.title": "Una villa vista mare con terrazze e giardini",
    "compare.card4.copy": "L'alternativa serena ai grandi hotel della Costiera Amalfitana, con spazi esterni e alcune delle migliori viste sul Golfo.",
    "compare.card5.title": "Una sensazione locale lontano dalle zone più affollate",
    "compare.card5.copy": "Soggiorna sopra Vietri sul Mare e vivi la costa da un borgo più intimo.",
    "audience.kicker": "Per coppie, famiglie e amanti dello slow travel",
    "audience.title": "Una villa sul mare per un viaggio diverso",
    "audience.copy": "Villa San Vito è perfetta per coppie in cerca di una fuga romantica, amici che desiderano un soggiorno più lento sulla costa, e famiglie o piccoli gruppi che preferiscono un'esperienza di casa. Qui puoi vivere un po' più come un italiano: piano, tranquillo, guardando il mare tra i limoni, con buon cibo, aria aperta e un indimenticabile calice di vino.",
    "villa.kicker": "La villa",
    "villa.title": "Una casa, tre spazi: un livello per ogni esigenza",
    "villa.copy": "Villa San Vito si sviluppa su tre livelli, ognuno pensato per un momento diverso del soggiorno: spazi sociali aperti, camere tranquille e terrazze per vivere la costa senza fretta.",
    "villa.stat.levels": "livelli",
    "villa.stat.bedrooms": "camere",
    "villa.stat.beds": "letti",
    "villa.stat.bathrooms": "bagni",
    "villa.stat.viewsLabel": "Mare",
    "villa.stat.views": "vista sul Golfo",
    "villa.stat.gardenLabel": "Giardino",
    "villa.stat.garden": "spazio esterno privato",
    "villa.stat.wifi": "connessione veloce",
    "villa.stat.parkingLabel": "Parking",
    "villa.stat.parking": "dentro la proprietà",
    "villa.ground.title": "Piano terra",
    "villa.ground.copy": "Un ampio soggiorno, una cucina completamente attrezzata e la zona pranzo si aprono verso la terrazza arredata e il giardino privato. Un bagno esterno aggiunge praticità per il tempo trascorso all'aperto.",
    "villa.first.title": "Primo piano",
    "villa.first.copy": "Una zona lavoro e studio si affianca a due camere con letti singoli, un bagno completo e una doccia separata, offrendo flessibilità e angoli tranquilli.",
    "villa.second.title": "Secondo piano",
    "villa.second.copy": "La camera principale dispone di letto matrimoniale, bagno con vasca e ampia terrazza con vista sul Golfo di Salerno.",
    "villa.outdoor.title": "Spazi esterni",
    "villa.outdoor.copy": "Il giardino privato, l'albero di limoni, le terrazze arredate e la vista verso il mare definiscono la vita all'aperto della proprietà.",
    "gallery.kicker": "Viste e interni",
    "gallery.title": "Luce mediterranea, terrazze con giardino e interni generosi",
    "gallery.note": "Scene selezionate dalle terrazze, dal giardino, dagli interni e dal contesto costiero.",
    "gallery.item1": "Terrazza e vista mare",
    "gallery.item2": "Giardino privato",
    "gallery.item3": "Albero di limoni",
    "gallery.item4": "Cucina",
    "gallery.item5": "Dettagli della sala da pranzo",
    "gallery.item6": "Tavola apparecchiata",
    "gallery.item7": "Camera principale",
    "gallery.item8": "Camere singole",
    "gallery.item9": "Arco interno",
    "gallery.item10": "Soggiorno",
    "gallery.item11": "Salottino",
    "location.kicker": "Posizione",
    "location.title": "Raito, sopra Vietri sul Mare",
    "location.copy": "Raito è un borgo tranquillo sopra Vietri sul Mare, conosciuto per le sue viste, l'atmosfera calma e la vicinanza a Salerno. Da qui gli ospiti possono esplorare la Costiera Amalfitana e rientrare a fine giornata in una base privata e serena.",
    "location.note": "Il sito mostra l'area generale. I dettagli esatti dell'indirizzo possono essere gestiti tramite la piattaforma di prenotazione.",
    "nearby.kicker": "Esplora la costa",
    "nearby.title": "La base perfetta per esplorare il meglio della Costiera Amalfitana",
    "nearby.intro": "Da Villa San Vito puoi visitare in giornata alcuni dei luoghi più belli della zona.",
    "nearby.vietri": "Un vicino borgo costiero noto per le ceramiche, la vista mare e il carattere locale.",
    "nearby.salerno": "Un punto d'appoggio pratico per trasporti, ristoranti e passeggiate sul lungomare vicino alla Costiera Amalfitana.",
    "nearby.amalfi": "Una tappa classica della Costiera Amalfitana e una bella gita dalla villa.",
    "nearby.ravello": "Un raffinato borgo collinare amato per giardini, viste e patrimonio culturale.",
    "nearby.positano": "Un celebre borgo verticale sul mare, raggiungibile come parte di un itinerario costiero.",
    "nearby.pompeii": "Un sito archeologico essenziale per chi ama la storia romana.",
    "nearby.paestum": "Una gita appagante tra templi greci, archeologia e paesaggi aperti.",
    "booking.kicker": "Prenotazioni",
    "booking.title": "Prenota Villa San Vito tramite la tua piattaforma preferita",
    "booking.copy": "Prenotazioni, pagamenti, disponibilità e politiche di cancellazione sono gestiti direttamente da Airbnb, Booking e Vrbo. Scegli la piattaforma che preferisci e completa lì la tua prenotazione in modo sicuro.",
    "booking.airbnb.copy": "Consulta l'annuncio Airbnb, le recensioni e i dettagli di prenotazione.",
    "booking.booking.copy": "Confronta disponibilità, politiche e informazioni per viaggiatori su Booking.",
    "booking.vrbo.copy": "Consulta l'annuncio Vrbo e i dettagli di prenotazione.",
    "booking.disclaimer": "Questo sito è una vetrina informativa per Villa San Vito. Le prenotazioni dirette non vengono elaborate qui.",
    "reviews.kicker": "Recensioni verificate",
    "reviews.title": "Cosa dicono gli ospiti dopo aver vissuto l'esperienza Villa San Vito",
    "reviews.airbnb": "Valutazione Airbnb",
    "reviews.count": "14 recensioni",
    "reviews.highlights": "Aspetti citati dagli ospiti: vista, ospitalità, posizione, parcheggio, spazi esterni e comfort.",
    "reviews.placeholder": "È un posto molto buono. Vista spettacolare da un enorme patio sul retro. L'alloggio era in buone condizioni. Molto consigliato. Il parcheggio è un po' stretto, ma ce lo avevano comunicato bene, quindi non ci sono state sorprese.",
    "reviews.link": "Leggi le recensioni su Airbnb",
    "reviews.note": "La cronologia completa delle recensioni e i dettagli delle piattaforme sono disponibili negli annunci di prenotazione.",
    "faq.kicker": "Prima di prenotare",
    "faq.title": "Domande frequenti",
    "faq.1.q": "Villa San Vito è uno dei migliori posti dove soggiornare in Costiera Amalfitana?",
    "faq.1.a": "Villa San Vito è una casa vacanza privata a Raito, ideale per chi si chiede dove soggiornare in Costiera Amalfitana e cerca vista mare, privacy e più spazio rispetto a una camera d'hotel tradizionale.",
    "faq.2.q": "Villa San Vito è un hotel o una villa privata?",
    "faq.2.a": "Villa San Vito non è un hotel. È una villa privata in Costiera Amalfitana disponibile tramite Airbnb, Booking e Vrbo.",
    "faq.3.q": "È una buona alternativa agli hotel di lusso in Costiera Amalfitana?",
    "faq.3.a": "Sì, per chi preferisce privacy, terrazze, giardino e atmosfera locale invece dei servizi alberghieri, Villa San Vito può essere una forte alternativa agli hotel di lusso in Costiera Amalfitana.",
    "faq.4.q": "Villa San Vito è adatta alle famiglie?",
    "faq.4.a": "Sì. Le famiglie che confrontano hotel per famiglie in Costiera Amalfitana possono apprezzare le tre camere, la cucina completa, il parcheggio, gli spazi esterni e lo spazio per fino a sei ospiti.",
    "faq.5.q": "Villa San Vito è adatta alle coppie?",
    "faq.5.a": "Sì. Le coppie che cercano una villa costiera italiana o un'alternativa agli hotel per luna di miele in Costiera Amalfitana possono apprezzare le terrazze tranquille, la vista mare e il contesto privato.",
    "faq.6.q": "Villa San Vito è fronte mare?",
    "faq.6.a": "Villa San Vito non è descritta come un hotel fronte mare. È una villa vista mare a Raito, sopra Vietri sul Mare, con vista verso il Golfo di Salerno.",
    "faq.7.q": "Villa San Vito è all inclusive?",
    "faq.7.a": "No. Villa San Vito non è un resort all-inclusive in Costiera Amalfitana. È una casa vacanza privata con cucina, giardino, terrazze e prenotazione tramite piattaforme esterne.",
    "faq.8.q": "Posso prenotare direttamente su questo sito?",
    "faq.8.a": "No. Tutte le prenotazioni si completano tramite Airbnb, Booking o Vrbo.",
    "footer.reservations": "Le prenotazioni sono gestite esclusivamente tramite Airbnb, Booking e Vrbo."
  }
};

const header = document.querySelector(".site-header");
const languageButtons = document.querySelectorAll("[data-lang]");
const translatableNodes = document.querySelectorAll("[data-i18n]");
const galleryDialog = document.querySelector(".gallery-dialog");
const galleryDialogImage = galleryDialog?.querySelector("img");
const galleryDialogCaption = galleryDialog?.querySelector("p");
const galleryClose = galleryDialog?.querySelector(".dialog-close");

function setLanguage(language) {
  const selectedLanguage = translations[language] ? language : "en";
  document.documentElement.lang = selectedLanguage;

  translatableNodes.forEach((node) => {
    const key = node.dataset.i18n;
    const value = translations[selectedLanguage][key];
    if (value) {
      node.textContent = value;
    }
  });

  languageButtons.forEach((button) => {
    const isActive = button.dataset.lang === selectedLanguage;
    button.classList.toggle("is-active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("villaSanVitoLanguage", selectedLanguage);
}

function updateHeaderState() {
  header?.classList.toggle("is-scrolled", window.scrollY > 24);
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

document.querySelectorAll(".gallery-item").forEach((item) => {
  item.addEventListener("click", () => {
    if (!galleryDialog || !galleryDialogImage || !galleryDialogCaption) {
      return;
    }

    const image = item.querySelector("img");
    const caption = item.querySelector("span")?.textContent || image?.alt || "";
    galleryDialogImage.src = item.dataset.full || image?.src || "";
    galleryDialogImage.alt = image?.alt || caption;
    galleryDialogCaption.textContent = caption;
    galleryDialog.showModal();
  });
});

galleryClose?.addEventListener("click", () => galleryDialog?.close());

galleryDialog?.addEventListener("click", (event) => {
  if (event.target === galleryDialog) {
    galleryDialog.close();
  }
});

window.addEventListener("scroll", updateHeaderState, { passive: true });
updateHeaderState();

setLanguage(localStorage.getItem("villaSanVitoLanguage") || "en");
