// EDIT TEXTS: update multilingual copy here. Keep keys aligned with data-i18n attributes in index.html.
const translations = {
  it: {
    skip: "Vai al contenuto",
    "nav.history": "Storia",
    "nav.villa": "Villa",
    "nav.territory": "Territorio",
    "nav.outdoors": "Esterni",
    "nav.services": "Servizi",
    "nav.book": "Prenotazioni",
    "opening.kicker": "Costiera Amalfitana",
    "opening.title": "Villa San Vito",
    "aria.primaryNavigation": "Navigazione principale",
    "aria.brandHome": "Home di Villa San Vito",
    "aria.mainMenu": "Menu principale",
    "aria.languageSwitcher": "Selettore lingua",
    "aria.villaInlinePhotos": "Dettagli interni della villa",
    "aria.outdoorsInlinePhotos": "Sequenza fotografica degli esterni",
    "aria.bookingPlatforms": "Piattaforme di prenotazione",
    "aria.socialMedia": "Canali social",
    "alt.hero": "Facciata storica di Villa San Vito tra le palme",
    "alt.about": "La famiglia di Villa San Vito riunita sulla terrazza affacciata sul Golfo",
    "alt.history": "Raito e Vietri in un dipinto di Josef Rabel del 1819",
    "alt.historyVillage": "Veduta panoramica del borgo di Raito tra il mare e la montagna",
    "alt.gardenDetail": "Dettaglio del giardino con vaso in terracotta e gerani",
    "alt.gardenPath": "Passaggio esterno tra la villa, le palme e il giardino",
    "alt.atticBedroom": "Camera mansardata con letto e dettagli nei toni del mare",
    "alt.livingRoom": "Soggiorno luminoso con arredi mediterranei e finestra ad arco",
    "alt.livingDining": "Soggiorno e zona pranzo con arco azzurro e camino",
    "alt.lemonBooks": "Limoni e libri su un mobile in legno",
    "alt.fireplaceMap": "Camino bianco con mappa antica e dettagli mediterranei",
    "alt.stairDetail": "Dettaglio della scala interna in ferro e legno",
    "alt.villaSign": "Targa in ceramica Villa San Vito",
    "alt.lantern": "Lanterna decorativa su pavimento in cotto",
    "alt.lemonView": "Limoni con vista sul mare della Costiera Amalfitana",
    "alt.coastSeascape": "Paesaggio marino della Costiera Amalfitana visto dalla costa",
    "alt.territoryCoast": "Veduta della costa con torre sul mare e scogli",
    "alt.territoryArchaeology": "Cupole decorate e campanile di un borgo della Costiera Amalfitana",
    "alt.territoryRavelloTerrace": "Terrazza panoramica di Ravello con statue e vista sulla Costiera Amalfitana",
    "alt.territoryPaestumTemples": "Templi greci di Paestum tra pini mediterranei e rovine archeologiche",
    "alt.villaDiningArch": "Zona pranzo con arco azzurro e vista sul soggiorno",
    "alt.villaLivingStaircase": "Soggiorno con scala interna, lampadario e pavimento in cotto",
    "alt.villaStudyFireplace": "Camino dello studio con mappa antica e dettagli mediterranei",
    "alt.villaBedroomTowels": "Asciugamani preparati sul letto con cuscini nei toni del mare",
    "alt.villaBedroomBlue": "Camera da letto con biancheria e asciugamani per gli ospiti",
    "alt.outdoorsSeaTerrace": "Terrazza panoramica con sdraio e vista sul mare",
    "alt.outdoorsMagnoliaGarden": "Giardino ombreggiato con magnolia e prato verde",
    "alt.outdoorsTerraceDiningSea": "Tavolo esterno all'ombra con vista sul mare",
    "alt.outdoorsGardenCorner": "Facciata della villa con tavolino bianco, palme e giardino",
    "alt.outdoorsFacadeBench": "Panca con cuscini azzurri sulla facciata della villa",
    "alt.servicesMap": "Mappa illustrata della Costiera Amalfitana",
    "alt.garage": "Cancello di accesso al parcheggio privato della villa",
    "alt.pets": "Cane accolto a Villa San Vito",
    "pets.short": "Siamo inoltre amici degli animali",
    "about.kicker": "Chi siamo",
    "about.title": "Chi siamo",
    "about.copy": "Siamo una famiglia profondamente legata alla Costiera Amalfitana. Dal 2023 ci dedichiamo con gioia all'arte dell'accoglienza. Il nostro desiderio più grande è aprirvi le porte di casa e farvi scoprire uno dei luoghi più belli del mondo, offrendovi un'oasi di pace, fascino e autentico relax.",
    "about.cta": "Contattaci",
    "welcome.title": "Benvenuti a Villa San Vito",
    "welcome.copy": "Situata a Raito, uno dei borghi più autentici della Costiera Amalfitana, Villa San Vito domina il Golfo di Salerno da una posizione privilegiata e silenziosa, sospesa tra il mare e il grande giardino dai profumi mediterranei e i classici pergolati di limoni.",
    "history.kicker": "A. Storia",
    "history.title": "Una posizione strategica tra mare, arte e cultura",
    "history.copy": "Raito conserva una memoria antica, fatta di luce, ceramica e silenzio. Arroccato sulla roccia e affacciato sul Golfo, questo lembo di terra dona alla villa il suo carattere più intimo: pietra viva, terrazze panoramiche, brezza marina e un tempo che scorre lento, senza fretta.",
    "history.copy2": "Villa San Vito custodisce e racconta questa storia. La sua anima ottocentesca dialoga armoniosamente con l'architettura locale: gli ambienti interni sono freschi, protetti da ampie mura antiche, mentre i sentieri esterni si snodano tra gli alberi di limoni, svelando scorci unici e panorami mozzafiato che abbracciano, dall'alto, la vicina Vietri sul Mare.",
    "history.caption": "Raito e Vietri in un dipinto di Josef Rabel, 1819",
    "territory.kicker": "B. Territorio",
    "territory.title": "Esplorare la Costiera e i suoi Borghi",
    "territory.copy": "Villa San Vito si trova in una posizione privilegiata tra Vietri sul Mare e Cetara, immersa in una zona tranquilla e panoramica dove la Costiera Amalfitana comincia ad aprirsi verso il Golfo di Salerno. Questo angolo di paradiso unisce la massima riservatezza alla comodità di avere a portata di mano le mete più affascinanti della Campania.",
    "territory.coast.title": "Esplorare la Costiera e i suoi Borghi",
    "territory.coast.intro": "Dalla villa è possibile muoversi agevolmente alla scoperta dei borghi più celebri della costa, scegliendo tra diverse modalità di viaggio.",
    "territory.coast.road": "In auto, in scooter o con i bus locali lungo la Statale Amalfitana: una delle strade più panoramiche del mondo vi collegherà direttamente a Salerno, ideale anche per l'alta velocità ferroviaria, a Vietri che vi accoglierà con le sue storiche ceramiche colorate, mentre Cetara vi delizierà con la sua autentica tradizione marinara e la famosa colatura di alici. Proseguendo, troverete il piccolo borgo di Minori, la romantica Ravello sospesa tra cielo e mare, Amalfi con il suo duomo maestoso, Praiano e il fiordo di Furore, fino all'iconica Positano.",
    "territory.coast.sea": "Via mare con traghetti, aliscafi e taxi boat: per un'esperienza senza stress, i moli di Salerno, Vietri e Cetara offrono collegamenti marittimi veloci. Potrete navigare ammirando e raggiungendo tutti i piccoli borghi oltre all'isola di Capri, per poi rientrare comodamente, a fine pomeriggio, nella calma e nel silenzio del borgo.",
    "territory.history.title": "Archeologia e Storia a Breve Distanza",
    "territory.history.copy": "La villa è anche la base perfetta per escursioni giornaliere dedicate alla storia antica.",
    "territory.history.places": "Pompei ed Ercolano, per un tuffo indimenticabile nella storia romana, camminando tra le rovine perfettamente conservate all'ombra del Vesuvio, e Paestum, dove potrete ammirare i maestosi templi greci magnificamente conservati e concedervi una sosta nei rinomati caseifici della Piana del Sele.",
    "villa.kicker": "C. Villa",
    "villa.title": "Il fascino di una casa storica, da vivere e respirare",
    "villa.copy": "Chi sceglie Villa San Vito non cerca il ritmo frenetico di un hotel, ma l'abbraccio di una casa privata. Troverete una casa pensata per rigenerarvi e recuperare il vostro tempo: il caffè del mattino in terrazza con vista sul mare, la frescura del pomeriggio all'ombra del giardino, il silenzio delle stanze e lo sguardo che, inevitabilmente, si perde nell'azzurro del mare.",
    "villa.copy2": "Sviluppata su tre livelli, la villa vi accoglie al piano terra con una zona giorno pensata per il relax e la convivialità con un ampio soggiorno, una spaziosa cucina completamente attrezzata e una zona pranzo perfetta per i momenti in compagnia.",
    "villa.copy3": "Ai piani superiori, tre camere da letto sia singole che matrimoniali con bagni ai piani e una comoda doccia separata per la massima praticità di tutti gli ospiti.",
    "villa.copy4": "Troverete inoltre una zona studio con un suggestivo camino e una magnifica terrazza da cui ammirare una splendida vista sul Golfo di Salerno.",
    "villa.copy5": "A completare i servizi della villa, troverete due posti auto privati all'aperto, completamente gratuiti e a vostra completa disposizione per l'intera durata del soggiorno.",
    "outdoors.kicker": "D. Esterni",
    "outdoors.title": "Oltre le mura, l'esperienza continua",
    "outdoors.copyGarden": "Il vero fiore all'occhiello della villa è senza dubbio il suo grande giardino.",
    "outdoors.copyExtension": "Più che un semplice spazio esterno, è un prolungamento della casa stessa, pensato per essere vissuto in ogni momento della giornata.",
    "outdoors.copyTime": "Qui il tempo sembra quasi rallentare: ci si può svegliare con una colazione al sole, rifugiarsi all'ombra degli alberi nel pomeriggio o godersi la sera mentre in lontananza si accendono le luci del Golfo.",
    "outdoors.copyTable": "Tra terrazza arredata, angoli d'ombra e piante rigogliose, c'è anche un grande tavolo che sembra fatto apposta per dimenticarsi dell'orologio e prolungare il piacere di stare insieme.",
    "outdoors.copyPanorama": "Il panorama che si gode da quassù è semplicemente mozzafiato, un'esperienza unica e suggestiva che vi accompagnerà per tutto il vostro soggiorno.",
    "services.kicker": "E. Servizi",
    "services.title": "Le nostre attenzioni per voi",
    "services.season": "Villa San Vito vi accoglie dal 1 marzo al 1 novembre e dal 23 dicembre al 3 gennaio.",
    "services.connections.title": "Collegamenti",
    "services.connections.lead": "Vivi la Costiera Amalfitana senza pensieri, via terra e via mare.",
    "services.connections.transfer": "Il tuo viaggio comincia nel momento in cui arrivi. Dimentica lo stress del traffico e lasciati guidare: organizziamo per te transfer esclusivi con autista privato e comodi shuttle da e per gli aeroporti e le stazioni di Napoli e Salerno.",
    "services.connections.question": "Vuoi scoprire la magia della Costiera da una prospettiva unica? Scegli come vivere la tua avventura:",
    "services.connections.land.label": "Via terra",
    "services.connections.land.copy": "A bordo di auto di classe per ammirare i panorami mozzafiato.",
    "services.connections.sea.label": "Via mare",
    "services.connections.sea.copy": "Cullato dalle onde su imbarcazioni private, con la libertà di guidare o di affidarti a un marinaio esperto.",
    "services.connections.note": "Tutti i servizi di trasporto ed escursione sono personalizzati e disponibili su prenotazione. Contattaci in anticipo per disegnare insieme la tua esperienza su misura. I servizi premium sono soggetti a supplemento.",
    "services.parking.title": "Parcheggio",
    "services.parking.copy": "La villa è dotata di un parcheggio interno e gratuito per gli ospiti della struttura.",
    "services.pets.title": "Siamo anche amici degli animali",
    "services.pets.copy": "Siamo felici di accogliere i vostri animali domestici. Tuttavia, per garantire il comfort e la tranquillità di tutti i nostri ospiti, vi chiediamo di informarci della loro presenza al momento della prenotazione e di assicurarvi che siano abituati alla convivenza e rispettino la pace e la quiete della proprietà.",
    "services.contact.title": "Contattaci",
    "services.contact.copy": "Per informazioni, richieste particolari e prenotazione dei servizi, scriveteci: saremo felici di aiutarvi a organizzare il vostro soggiorno.",
    "booking.kicker": "F. Prenota",
    "booking.title": "Prenotazioni tramite piattaforme esterne",
    "booking.copy": "Villa San Vito non gestisce prenotazioni dirette dal sito. Disponibilità, condizioni e pagamenti sono gestiti sulle piattaforme esterne.",
    "contact.email.label": "Contattaci via email",
    "instagram.copy": "Momenti recenti e viste della casa sono anche su",
    "footer.location": "Raito, Vietri sul Mare, Campania, Italia",
    "footer.reservations": "Prenotazioni gestite esclusivamente tramite Airbnb, Booking e Vrbo.",
    "footer.registration": "Codice di registrazione",
    "footer.powered": "Realizzato da"
  },

  es: {
    skip: "Saltar al contenido",
    "nav.history": "Historia",
    "nav.villa": "Villa",
    "nav.territory": "Territorio",
    "nav.outdoors": "Exteriores",
    "nav.services": "Servicios",
    "nav.book": "Reservas",
    "opening.kicker": "Costa Amalfitana",
    "opening.title": "Villa San Vito",
    "aria.primaryNavigation": "Navegación principal",
    "aria.brandHome": "Inicio de Villa San Vito",
    "aria.mainMenu": "Menú principal",
    "aria.languageSwitcher": "Selector de idioma",
    "aria.villaInlinePhotos": "Detalles interiores de la villa",
    "aria.outdoorsInlinePhotos": "Secuencia fotográfica de los exteriores",
    "aria.bookingPlatforms": "Plataformas de reserva",
    "aria.socialMedia": "Redes sociales",
    "alt.hero": "Fachada histórica de Villa San Vito entre palmeras",
    "alt.about": "La familia de Villa San Vito reunida en la terraza con vistas al Golfo",
    "alt.history": "Raito y Vietri en una pintura de Josef Rabel de 1819",
    "alt.historyVillage": "Vista panorámica del pueblo de Raito entre el mar y la montaña",
    "alt.gardenDetail": "Detalle del jardín con maceta de terracota y geranios",
    "alt.gardenPath": "Pasaje exterior entre la villa, las palmeras y el jardín",
    "alt.atticBedroom": "Dormitorio abuhardillado con cama y detalles en tonos marinos",
    "alt.livingRoom": "Salón luminoso con decoración mediterránea y ventana arqueada",
    "alt.livingDining": "Salón y comedor con arco azul y chimenea",
    "alt.lemonBooks": "Limones y libros sobre un mueble de madera",
    "alt.fireplaceMap": "Chimenea blanca con mapa antiguo y detalles mediterráneos",
    "alt.stairDetail": "Detalle de la escalera interior de hierro y madera",
    "alt.villaSign": "Placa de cerámica de Villa San Vito",
    "alt.lantern": "Farol decorativo sobre suelo de terracota",
    "alt.lemonView": "Limones con vistas al mar de la Costa Amalfitana",
    "alt.coastSeascape": "Paisaje marino de la Costa Amalfitana visto desde la costa",
    "alt.territoryCoast": "Vista de la costa con una torre junto al mar y formaciones rocosas",
    "alt.territoryArchaeology": "Cúpulas decoradas y campanario de un pueblo de la Costa Amalfitana",
    "alt.territoryRavelloTerrace": "Terraza panorámica de Ravello con estatuas y vista a la Costa Amalfitana",
    "alt.territoryPaestumTemples": "Templos griegos de Paestum entre pinos mediterráneos y ruinas arqueológicas",
    "alt.villaDiningArch": "Comedor con arco azul y vista al salón",
    "alt.villaLivingStaircase": "Salón con escalera interior, lámpara y suelo de terracota",
    "alt.villaStudyFireplace": "Chimenea del estudio con mapa antiguo y detalles mediterráneos",
    "alt.villaBedroomTowels": "Toallas preparadas sobre la cama con cojines en tonos marinos",
    "alt.villaBedroomBlue": "Dormitorio con ropa de cama y toallas para los huéspedes",
    "alt.outdoorsSeaTerrace": "Terraza panorámica con tumbona y vista al mar",
    "alt.outdoorsMagnoliaGarden": "Jardín sombreado con magnolio y césped verde",
    "alt.outdoorsTerraceDiningSea": "Mesa exterior a la sombra con vista al mar",
    "alt.outdoorsGardenCorner": "Fachada de la villa con una mesa blanca, palmeras y jardín",
    "alt.outdoorsFacadeBench": "Banco con cojines azules junto a la fachada de la villa",
    "alt.servicesMap": "Mapa ilustrado de la Costa Amalfitana",
    "alt.garage": "Puerta de acceso al estacionamiento privado de la villa",
    "alt.pets": "Perro recibido en Villa San Vito",
    "pets.short": "También somos amigos de los animales",
    "about.kicker": "Quiénes somos",
    "about.title": "Quiénes somos",
    "about.copy": "Somos una familia profundamente ligada a la Costa Amalfitana. Desde 2023 nos dedicamos con alegría al arte de la hospitalidad. Nuestro mayor deseo es abrirles las puertas de casa y hacerles descubrir uno de los lugares más bellos del mundo, ofreciéndoles un oasis de paz, encanto y auténtico relax.",
    "about.cta": "Contáctenos",
    "welcome.title": "Bienvenidos a Villa San Vito",
    "welcome.copy": "Ubicada en Raito, uno de los pueblos más auténticos de la Costa Amalfitana, Villa San Vito domina el Golfo de Salerno desde una posición privilegiada y silenciosa, suspendida entre el mar, el gran jardín de aromas mediterráneos y los clásicos pergolados de limoneros.",
    "history.kicker": "A. Historia",
    "history.title": "Una ubicación estratégica entre mar, arte y cultura",
    "history.copy": "Raito conserva una memoria antigua, hecha de luz, cerámica y silencio. Encaramado sobre la roca y mirando al Golfo, este rincón de tierra le da a la villa su carácter más íntimo: piedra viva, terrazas panorámicas, brisa marina y un tiempo que transcurre lento, sin prisa.",
    "history.copy2": "Villa San Vito custodia y cuenta esta historia. Su alma del siglo XIX dialoga armoniosamente con la arquitectura local: los interiores son frescos, protegidos por amplios muros antiguos, mientras los senderos exteriores se abren entre los limoneros, revelando rincones únicos y panoramas impresionantes que abrazan, desde lo alto, la cercana Vietri sul Mare.",
    "history.caption": "Raito y Vietri en una pintura de Josef Rabel, 1819",
    "territory.kicker": "B. Territorio",
    "territory.title": "Explorar la Costa Amalfitana y sus pueblos",
    "territory.copy": "Villa San Vito se encuentra en una posición privilegiada entre Vietri sul Mare y Cetara, inmersa en una zona tranquila y panorámica donde la Costa Amalfitana comienza a abrirse hacia el Golfo de Salerno. Este rincón de paraíso combina la máxima privacidad con la comodidad de tener al alcance los destinos más fascinantes de Campania.",
    "territory.coast.title": "Explorar la costa y sus pueblos",
    "territory.coast.intro": "Desde la villa es fácil descubrir los pueblos más célebres de la costa, eligiendo entre diferentes formas de viajar.",
    "territory.coast.road": "En coche, scooter o autobús local por la carretera Amalfitana: una de las rutas más panorámicas del mundo conecta directamente con Salerno, ideal también para los trenes de alta velocidad, con Vietri y sus históricas cerámicas de colores, y con Cetara, su auténtica tradición marinera y la famosa colatura de anchoas. Continuando aparecen Minori, la romántica Ravello, Amalfi con su majestuosa catedral, Praiano y el fiordo de Furore, hasta la icónica Positano.",
    "territory.coast.sea": "Por mar, mediante ferris, hidroalas y taxi boat: los puertos de Salerno, Vietri y Cetara ofrecen conexiones marítimas rápidas. Podrán navegar contemplando y visitando los pequeños pueblos y la isla de Capri, para regresar cómodamente al final de la tarde a la calma y el silencio de Raito.",
    "territory.history.title": "Arqueología e historia a poca distancia",
    "territory.history.copy": "La villa también es una base perfecta para excursiones de un día dedicadas a la historia antigua.",
    "territory.history.places": "Pompeya y Herculano ofrecen una inmersión inolvidable en la historia romana, caminando entre ruinas perfectamente conservadas a la sombra del Vesubio. En Paestum podrán admirar los majestuosos templos griegos y hacer una parada en las reconocidas queserías de la llanura del Sele.",
    "villa.kicker": "C. Villa",
    "villa.title": "El encanto de una casa histórica, para vivir y respirar",
    "villa.copy": "Quienes eligen Villa San Vito no buscan el ritmo frenético de un hotel, sino el abrazo de una casa privada. Encontrarás una casa diseñada para regenerarte y recuperar tu tiempo: el café de la mañana en la terraza con vistas al mar, el frescor de la tarde a la sombra del jardín, el silencio de las habitaciones y la mirada que, inevitablemente, se pierde en el azul del mar.",
    "villa.copy2": "Distribuida en tres niveles, la villa recibe en la planta baja con una zona de día pensada para el descanso y la convivencia: un amplio salón, una cocina espaciosa y completamente equipada y un comedor perfecto para compartir.",
    "villa.copy3": "En las plantas superiores hay tres dormitorios, individuales y matrimoniales, con baños en las plantas y una cómoda ducha separada para la máxima practicidad de todos los huéspedes.",
    "villa.copy4": "También encontrarán una zona de estudio con una sugerente chimenea y una magnífica terraza desde la que admirar la espléndida vista del Golfo de Salerno.",
    "villa.copy5": "La villa se completa con dos plazas de estacionamiento privadas al aire libre, totalmente gratuitas y disponibles durante toda la estancia.",
    "outdoors.kicker": "D. Exteriores",
    "outdoors.title": "Más allá de los muros, la experiencia continúa",
    "outdoors.copyGarden": "La verdadera joya de la villa es, sin duda, su gran jardín.",
    "outdoors.copyExtension": "Más que un simple espacio exterior, es una prolongación de la casa, pensado para disfrutarse en cada momento del día.",
    "outdoors.copyTime": "Aquí el tiempo parece casi detenerse: se puede despertar con un desayuno al sol, refugiarse a la sombra de los árboles por la tarde o disfrutar la noche mientras a lo lejos se encienden las luces del Golfo.",
    "outdoors.copyTable": "Entre la terraza amueblada, los rincones de sombra y las plantas exuberantes, hay también una gran mesa que parece hecha para olvidarse del reloj y prolongar el placer de estar juntos.",
    "outdoors.copyPanorama": "El panorama desde aquí es sencillamente impresionante, una experiencia única y sugerente que acompañará toda la estancia.",
    "services.kicker": "E. Servicios",
    "services.title": "Nuestras atenciones para ustedes",
    "services.season": "Villa San Vito recibe a sus huéspedes del 1 de marzo al 1 de noviembre y del 23 de diciembre al 3 de enero.",
    "services.connections.title": "Conexiones",
    "services.connections.lead": "Viva la Costa Amalfitana sin preocupaciones, por tierra y por mar.",
    "services.connections.transfer": "Su viaje comienza desde el momento en que llega. Olvídese del estrés del tráfico y déjese guiar: organizamos traslados exclusivos con conductor privado y cómodos servicios de shuttle desde y hacia los aeropuertos y estaciones de Nápoles y Salerno.",
    "services.connections.question": "¿Quiere descubrir la magia de la Costa desde una perspectiva única? Elija cómo vivir su aventura:",
    "services.connections.land.label": "Por tierra",
    "services.connections.land.copy": "A bordo de vehículos de alta gama para admirar los impresionantes paisajes.",
    "services.connections.sea.label": "Por mar",
    "services.connections.sea.copy": "Mecido por las olas en embarcaciones privadas, con la libertad de conducir o confiar en un marinero experto.",
    "services.connections.note": "Todos los servicios de transporte y excursión son personalizados y están disponibles con reserva previa. Contáctenos con anticipación para diseñar juntos una experiencia a medida. Los servicios premium tienen un costo adicional.",
    "services.parking.title": "Estacionamiento",
    "services.parking.copy": "La villa dispone de estacionamiento interno y gratuito para los huéspedes de la propiedad.",
    "services.pets.title": "También somos amigos de los animales",
    "services.pets.copy": "Nos complace recibir a sus mascotas. Sin embargo, para garantizar la comodidad y la tranquilidad de todos nuestros huéspedes, les pedimos que nos informen de su presencia al realizar la reserva y que se aseguren de que estén acostumbradas a convivir y respeten la paz y la tranquilidad de la propiedad.",
    "services.contact.title": "Contáctenos",
    "services.contact.copy": "Para consultas, solicitudes especiales y reserva de servicios, escríbanos: estaremos encantados de ayudarle a organizar su estancia.",
    "booking.kicker": "F. Reservar",
    "booking.title": "Reservas a través de plataformas externas",
    "booking.copy": "Villa San Vito no gestiona reservas directas desde el sitio. La disponibilidad, las condiciones y los pagos se manejan en las plataformas externas.",
    "contact.email.label": "Contáctenos por correo electrónico",
    "instagram.copy": "También hay momentos recientes y vistas de la casa en",
    "footer.location": "Raito, Vietri sul Mare, Campania, Italia",
    "footer.reservations": "Reservas gestionadas exclusivamente a través de Airbnb, Booking y Vrbo.",
    "footer.registration": "Código de registro",
    "footer.powered": "Creado por"
  },

  en: {
    skip: "Skip to content",
    "nav.history": "History",
    "nav.villa": "Villa",
    "nav.territory": "Area",
    "nav.outdoors": "Outdoors",
    "nav.services": "Services",
    "nav.book": "Reservations",
    "opening.kicker": "Amalfi Coast",
    "opening.title": "Villa San Vito",
    "aria.primaryNavigation": "Main navigation",
    "aria.brandHome": "Villa San Vito home",
    "aria.mainMenu": "Main menu",
    "aria.languageSwitcher": "Language selector",
    "aria.villaInlinePhotos": "Interior details of the villa",
    "aria.outdoorsInlinePhotos": "Outdoor photographic sequence",
    "aria.bookingPlatforms": "Booking platforms",
    "aria.socialMedia": "Social media",
    "alt.hero": "Historic facade of Villa San Vito among palm trees",
    "alt.about": "The Villa San Vito family gathered on the terrace overlooking the Gulf",
    "alt.history": "Raito and Vietri in an 1819 painting by Josef Rabel",
    "alt.historyVillage": "Panoramic view of the village of Raito between the sea and the mountain",
    "alt.gardenDetail": "Garden detail with a terracotta pot and geraniums",
    "alt.gardenPath": "Outdoor passage between the villa, palm trees and garden",
    "alt.atticBedroom": "Attic bedroom with a bed and sea-toned details",
    "alt.livingRoom": "Bright living room with Mediterranean furnishings and an arched window",
    "alt.livingDining": "Living and dining area with a blue arch and fireplace",
    "alt.lemonBooks": "Lemons and books on a wooden cabinet",
    "alt.fireplaceMap": "White fireplace with an antique map and Mediterranean details",
    "alt.stairDetail": "Detail of the iron and wood interior staircase",
    "alt.villaSign": "Villa San Vito ceramic sign",
    "alt.lantern": "Decorative lantern on a terracotta floor",
    "alt.lemonView": "Lemons overlooking the sea of the Amalfi Coast",
    "alt.coastSeascape": "Amalfi Coast seascape viewed from the shore",
    "alt.territoryCoast": "Coastal view with a seaside tower and rock formations",
    "alt.territoryArchaeology": "Decorated domes and bell tower in an Amalfi Coast village",
    "alt.territoryRavelloTerrace": "Panoramic terrace in Ravello with statues and views of the Amalfi Coast",
    "alt.territoryPaestumTemples": "Greek temples of Paestum among Mediterranean pines and archaeological ruins",
    "alt.villaDiningArch": "Dining area with a blue arch and view toward the living room",
    "alt.villaLivingStaircase": "Living room with an interior staircase, chandelier and terracotta floor",
    "alt.villaStudyFireplace": "Study fireplace with an antique map and Mediterranean details",
    "alt.villaBedroomTowels": "Towels prepared on the bed with cushions in sea-inspired tones",
    "alt.villaBedroomBlue": "Bedroom with guest linens and towels",
    "alt.outdoorsSeaTerrace": "Panoramic terrace with a deck chair and sea view",
    "alt.outdoorsMagnoliaGarden": "Shaded garden with a magnolia tree and green lawn",
    "alt.outdoorsTerraceDiningSea": "Outdoor table in the shade with a sea view",
    "alt.outdoorsGardenCorner": "Villa facade with a white table, palm trees and garden",
    "alt.outdoorsFacadeBench": "Bench with blue cushions by the villa facade",
    "alt.servicesMap": "Illustrated map of the Amalfi Coast",
    "alt.garage": "Entrance gate to the villa's private parking area",
    "alt.pets": "Dog welcomed at Villa San Vito",
    "pets.short": "Pet Friendly",
    "about.kicker": "Who we are",
    "about.title": "Who we are",
    "about.copy": "We are a family deeply connected to the Amalfi Coast. Since 2023 we have joyfully dedicated ourselves to the art of hospitality. Our greatest wish is to open the doors of our home and help you discover one of the most beautiful places in the world, offering you an oasis of peace, charm and authentic relaxation.",
    "about.cta": "Contact us",
    "welcome.title": "Welcome to Villa San Vito",
    "welcome.copy": "Set in Raito, one of the most authentic villages of the Amalfi Coast, Villa San Vito overlooks the Gulf of Salerno from a privileged and quiet position, suspended between the sea, a large garden scented with Mediterranean fragrances and classic lemon pergolas.",
    "history.kicker": "A. History",
    "history.title": "A strategic position between sea, art and culture",
    "history.copy": "Raito preserves an ancient memory made of light, ceramics and silence. Perched on the rock and overlooking the Gulf, this strip of land gives the villa its most intimate character: living stone, panoramic terraces, sea breeze and a time that flows slowly, without hurry.",
    "history.copy2": "Villa San Vito preserves and tells this story. Its nineteenth-century soul speaks harmoniously with the local architecture: the interiors are cool, protected by wide ancient walls, while the outdoor paths wind among lemon trees, revealing unique glimpses and breathtaking views that embrace nearby Vietri sul Mare from above.",
    "history.caption": "Raito and Vietri in a painting by Josef Rabel, 1819",
    "territory.kicker": "B. The area",
    "territory.title": "Exploring the Amalfi Coast and its villages",
    "territory.copy": "Villa San Vito occupies a privileged position between Vietri sul Mare and Cetara, immersed in a quiet panoramic area where the Amalfi Coast begins to open toward the Gulf of Salerno. This corner of paradise combines complete privacy with the convenience of having Campania's most fascinating destinations within easy reach.",
    "territory.coast.title": "Exploring the coast and its villages",
    "territory.coast.intro": "From the villa, the coast's most celebrated villages can be explored easily, with several ways to travel.",
    "territory.coast.road": "By car, scooter or local bus along the Amalfi coastal road: one of the world's most scenic routes connects you directly to Salerno, also convenient for high-speed trains, to Vietri with its historic colorful ceramics, and to Cetara with its authentic fishing tradition and famous anchovy colatura. Continuing along the coast, you will find Minori, romantic Ravello, Amalfi and its majestic cathedral, Praiano and the Furore fjord, all the way to iconic Positano.",
    "territory.coast.sea": "By sea, using ferries, hydrofoils and water taxis: the ports of Salerno, Vietri and Cetara offer fast maritime connections. You can sail between the small coastal villages and Capri, then return comfortably at the end of the afternoon to the calm and silence of Raito.",
    "territory.history.title": "Archaeology and history within easy reach",
    "territory.history.copy": "The villa is also a perfect base for day trips devoted to ancient history.",
    "territory.history.places": "Pompeii and Herculaneum offer an unforgettable journey into Roman history among remarkably preserved ruins beneath Mount Vesuvius. At Paestum, you can admire the majestic Greek temples and stop at the renowned dairies of the Sele plain.",
    "villa.kicker": "C. Villa",
    "villa.title": "The charm of a historic house, to live in and breathe",
    "villa.copy": "Those who choose Villa San Vito are not looking for the frantic rhythm of a hotel, but the embrace of a private home. You will find a house designed to help you regenerate and recover your time: morning coffee on the terrace with sea views, the coolness of the afternoon in the shade of the garden, the silence of the rooms and a gaze that inevitably gets lost in the blue of the sea.",
    "villa.copy2": "Arranged over three levels, the villa welcomes you on the ground floor with a living area designed for relaxation and conviviality: a spacious sitting room, a large fully equipped kitchen and a dining area made for time together.",
    "villa.copy3": "The upper floors have three single and double bedrooms, with bathrooms on each level and a convenient separate shower for the comfort of every guest.",
    "villa.copy4": "There is also a study with an atmospheric fireplace and a magnificent terrace overlooking the Gulf of Salerno.",
    "villa.copy5": "Two private outdoor parking spaces, completely free and available throughout your stay, complete the villa's amenities.",
    "outdoors.kicker": "D. Outdoors",
    "outdoors.title": "Beyond the walls, the experience continues",
    "outdoors.copyGarden": "The villa's true highlight is undoubtedly its large garden.",
    "outdoors.copyExtension": "More than a simple outdoor space, it is an extension of the house itself, designed to be enjoyed at every moment of the day.",
    "outdoors.copyTime": "Here, time almost seems to slow: wake to breakfast in the sun, retreat beneath the trees in the afternoon, or enjoy the evening as the lights around the Gulf appear in the distance.",
    "outdoors.copyTable": "Between the furnished terrace, shaded corners and lush plants, there is also a large table that seems made for forgetting the time and prolonging the pleasure of being together.",
    "outdoors.copyPanorama": "The panorama from up here is simply breathtaking, a unique and evocative experience that will accompany you throughout your stay.",
    "services.kicker": "E. Services",
    "services.title": "Our thoughtful services for you",
    "services.season": "Villa San Vito welcomes guests from March 1 to November 1 and from December 23 to January 3.",
    "services.connections.title": "Transfers and connections",
    "services.connections.lead": "Experience the Amalfi Coast without worries, by land and by sea.",
    "services.connections.transfer": "Your journey begins the moment you arrive. Forget the stress of traffic and let us guide you: we can arrange exclusive private-driver transfers and convenient shuttles to and from the airports and railway stations of Naples and Salerno.",
    "services.connections.question": "Would you like to discover the magic of the Coast from a unique perspective? Choose how to experience your adventure:",
    "services.connections.land.label": "By land",
    "services.connections.land.copy": "Travel in premium vehicles while taking in the breathtaking scenery.",
    "services.connections.sea.label": "By sea",
    "services.connections.sea.copy": "Be carried by the waves aboard private boats, with the freedom to take the helm or rely on an experienced skipper.",
    "services.connections.note": "All transport and excursion services are personalized and available by advance reservation. Contact us early so we can design your tailor-made experience together. Premium services are subject to an additional charge.",
    "services.parking.title": "Parking",
    "services.parking.copy": "The villa provides free private on-site parking for guests.",
    "services.pets.title": "Pet Friendly",
    "services.pets.copy": "We are happy to welcome your pets. However, to ensure the comfort and tranquility of all our guests, we ask that you inform us of their presence at the time of booking and make sure they are used to living with others and respect the peace and quiet of the property.",
    "services.contact.title": "Contact us",
    "services.contact.copy": "For information, special requests and service reservations, write to us: we will be happy to help you organize your stay.",
    "booking.kicker": "F. Book",
    "booking.title": "Reservations through external platforms",
    "booking.copy": "Villa San Vito does not manage direct reservations through this site. Availability, conditions and payments are handled by the external platforms.",
    "contact.email.label": "Contact us by email",
    "instagram.copy": "Recent moments and views of the house are also on",
    "footer.location": "Raito, Vietri sul Mare, Campania, Italy",
    "footer.reservations": "Reservations are managed exclusively through Airbnb, Booking and Vrbo.",
    "footer.registration": "Registration code",
    "footer.powered": "Powered by"
  }
};

const languageButtons = document.querySelectorAll("[data-lang]");
const translatableNodes = document.querySelectorAll("[data-i18n]");
const ariaTranslatableNodes = document.querySelectorAll("[data-i18n-aria]");
const aboutImage = document.querySelector(".about-photo img");

if (aboutImage) {
  aboutImage.dataset.i18nAlt = "alt.about";
}

const altTranslatableNodes = document.querySelectorAll("[data-i18n-alt]");

const brandMark = document.querySelector(".brand img");
const openingHeading = document.querySelector(".opening-heading");

if (brandMark && openingHeading) {
  brandMark.classList.add("opening-brand-mark");
  brandMark.removeAttribute("width");
  brandMark.removeAttribute("height");
  openingHeading.prepend(brandMark);
}

function setLanguage(selectedLanguage) {
  const dictionary = translations[selectedLanguage] || translations.it;

  document.documentElement.lang = selectedLanguage;

  translatableNodes.forEach((node) => {
    const key = node.dataset.i18n;
    const value = dictionary[key];

    if (value) {
      node.textContent = value;
    }
  });

  ariaTranslatableNodes.forEach((node) => {
    const key = node.dataset.i18nAria;
    const value = dictionary[key];

    if (value) {
      node.setAttribute("aria-label", value);
    }
  });

  altTranslatableNodes.forEach((node) => {
    const key = node.dataset.i18nAlt;
    const value = dictionary[key];

    if (value) {
      node.setAttribute("alt", value);
    }
  });

  languageButtons.forEach((button) => {
    const isActive = button.dataset.lang === selectedLanguage;
    button.classList.toggle("is-active", isActive);
    button.setAttribute("aria-pressed", String(isActive));
  });

  localStorage.setItem("villaSanVitoLanguage", selectedLanguage);
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

setLanguage(localStorage.getItem("villaSanVitoLanguage") || "it");
